In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/100_Unique_QA_Dataset.csv')

In [3]:
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [4]:
df.isnull().value_counts()

question  answer
False     False     90
Name: count, dtype: int64

In [5]:
df.isna().value_counts()

question  answer
False     False     90
Name: count, dtype: int64

In [6]:
def tokenize(text):
  text = text.lower()
  text = text.replace('?', ' ')
  text = text.replace("'", "")
  return text.split()

In [7]:
tokenize('what is the capital of france?')

['what', 'is', 'the', 'capital', 'of', 'france']

In [8]:
vocab = {'<UNK>':0}

In [9]:
vocab = {}

def build_vocab(row):
    question_tokens = tokenize(row['question'])
    answer_tokens = tokenize(row['answer'])

    print("Q:", question_tokens)
    print("A:", answer_tokens)

    merged = question_tokens + answer_tokens

    for word in merged:
        if word not in vocab:
            vocab[word] = len(vocab)

In [10]:
df.apply(build_vocab, axis=1)

Q: ['what', 'is', 'the', 'capital', 'of', 'france']
A: ['paris']
Q: ['what', 'is', 'the', 'capital', 'of', 'germany']
A: ['berlin']
Q: ['who', 'wrote', 'to', 'kill', 'a', 'mockingbird']
A: ['harper-lee']
Q: ['what', 'is', 'the', 'largest', 'planet', 'in', 'our', 'solar', 'system']
A: ['jupiter']
Q: ['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius']
A: ['100']
Q: ['who', 'painted', 'the', 'mona', 'lisa']
A: ['leonardo-da-vinci']
Q: ['what', 'is', 'the', 'square', 'root', 'of', '64']
A: ['8']
Q: ['what', 'is', 'the', 'chemical', 'symbol', 'for', 'gold']
A: ['au']
Q: ['which', 'year', 'did', 'world', 'war', 'ii', 'end']
A: ['1945']
Q: ['what', 'is', 'the', 'longest', 'river', 'in', 'the', 'world']
A: ['nile']
Q: ['what', 'is', 'the', 'capital', 'of', 'japan']
A: ['tokyo']
Q: ['who', 'developed', 'the', 'theory', 'of', 'relativity']
A: ['albert-einstein']
Q: ['what', 'is', 'the', 'freezing', 'point', 'of', 'water', 'in', 'fahrenheit']
A: ['32']
Q: ['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet']
A: ['mars']
Q: ['who', 'is', 'the', 'author', 'of', '1984']
A: ['george-orwell']
Q: ['what', 'is', 'the', 'currency', 'of', 'the', 'united', 'kingdom']
A: ['pound']
Q: ['what', 'is', 'the', 'capital', 'of', 'india']
A: ['delhi']
Q: ['who', 'discovered', 'gravity']
A: ['newton']
Q: ['how', 'many', 'continents', 'are', 'there', 'on', 'earth']
A: ['7']
Q: ['which', 'gas', 'do', 'plants', 'use', 'for', 'photosynthesis']
A: ['co2']
Q: ['what', 'is', 'the', 'smallest', 'prime', 'number']
A: ['2']
Q: ['who', 'invented', 'the', 'telephone']
A: ['alexander-graham-bell']
Q: ['what', 'is', 'the', 'capital', 'of', 'australia']
A: ['canberra']
Q: ['which', 'ocean', 'is', 'the', 'largest']
A: ['pacific-ocean']
Q: ['what', 'is', 'the', 'speed', 'of', 'light', 'in', 'vacuum']
A: ['299,792,458m/s']
Q: ['which', 'language', 'is', 'spoken', 'in', 'brazil']
A: ['portuguese']
Q: ['who', 'discovered', 'penicillin']
A: ['alexander-fleming']
Q: ['what', 'is', 'the', 'capital', 'of', 'canada']
A: ['ottawa']
Q: ['what', 'is', 'the', 'largest', 'mammal', 'on', 'earth']
A: ['whale']
Q: ['which', 'element', 'has', 'the', 'atomic', 'number', '1']
A: ['hydrogen']
Q: ['what', 'is', 'the', 'tallest', 'mountain', 'in', 'the', 'world']
A: ['everest']
Q: ['which', 'city', 'is', 'known', 'as', 'the', 'big', 'apple']
A: ['newyork']
Q: ['how', 'many', 'planets', 'are', 'in', 'the', 'solar', 'system']
A: ['8']
Q: ['who', 'painted', 'starry', 'night']
A: ['vangogh']
Q: ['what', 'is', 'the', 'chemical', 'formula', 'of', 'water']
A: ['h2o']
Q: ['what', 'is', 'the', 'capital', 'of', 'italy']
A: ['rome']
Q: ['which', 'country', 'is', 'famous', 'for', 'sushi']
A: ['japan']
Q: ['who', 'was', 'the', 'first', 'person', 'to', 'step', 'on', 'the', 'moon']
A: ['armstrong']
Q: ['what', 'is', 'the', 'main', 'ingredient', 'in', 'guacamole']
A: ['avocado']
Q: ['how', 'many', 'sides', 'does', 'a', 'hexagon', 'have']
A: ['6']
Q: ['what', 'is', 'the', 'currency', 'of', 'china']
A: ['yuan']
Q: ['who', 'wrote', 'pride', 'and', 'prejudice']
A: ['jane-austen']
Q: ['what', 'is', 'the', 'chemical', 'symbol', 'for', 'iron']
A: ['fe']
Q: ['what', 'is', 'the', 'hardest', 'natural', 'substance', 'on', 'earth']
A: ['diamond']
Q: ['which', 'continent', 'is', 'the', 'largest', 'by', 'area']
A: ['asia']
Q: ['who', 'was', 'the', 'first', 'president', 'of', 'the', 'united', 'states']
A: ['george-washington']
Q: ['which', 'bird', 'is', 'known', 'for', 'its', 'ability', 'to', 'mimic', 'sounds']
A: ['parrot']
Q: ['what', 'is', 'the', 'longest-running', 'animated', 'tv', 'show']
A: ['simpsons']
Q: ['what', 'is', 'the', 'smallest', 'country', 'in', 'the', 'world']
A: ['vaticancity']
Q: ['which', 'planet', 'has', 'the', 'most', 'moons']
A: ['saturn']
Q: ['who', 'wrote', 'romeo', 'and', 'juliet']
A: ['shakespeare']
Q: ['what', 'is', 'the', 'main', 'gas', 'in', 'earths', 'atmosphere']
A: ['nitrogen']
Q: ['how', 'many', 'bones', 'are', 'in', 'the', 'adult', 'human', 'body']
A: ['206']
Q: ['which', 'metal', 'is', 'a', 'liquid', 'at', 'room', 'temperature']
A: ['mercury']
Q: ['what', 'is', 'the', 'capital', 'of', 'russia']
A: ['moscow']
Q: ['who', 'discovered', 'electricity']
A: ['benjamin-franklin']
Q: ['which', 'is', 'the', 'second-largest', 'country', 'by', 'land', 'area']
A: ['canada']
Q: ['what', 'is', 'the', 'color', 'of', 'a', 'ripe', 'banana']
A: ['yellow']
Q: ['which', 'month', 'has', '28', 'days', 'in', 'a', 'common', 'year']
A: ['february']
Q: ['what', 'is', 'the', 'study', 'of', 'living', 'organisms', 'called']
A: ['biology']
Q: ['which', 'country', 'is', 'home', 'to', 'the', 'great', 'wall']
A: ['china']
Q: ['what', 'do', 'bees', 'collect', 'from', 'flowers']
A: ['nectar']
Q: ['what', 'is', 'the', 'opposite', 'of', 'day']
A: ['night']
Q: ['what', 'is', 'the', 'capital', 'of', 'south', 'korea']
A: ['seoul']
Q: ['who', 'invented', 'the', 'light', 'bulb']
A: ['edison']
Q: ['which', 'gas', 'do', 'humans', 'breathe', 'in', 'for', 'survival']
A: ['oxygen']
Q: ['what', 'is', 'the', 'square', 'root', 'of', '144']
A: ['12']
Q: ['which', 'country', 'has', 'the', 'pyramids', 'of', 'giza']
A: ['egypt']
Q: ['which', 'sea', 'creature', 'has', 'eight', 'arms']
A: ['octopus']
Q: ['which', 'holiday', 'is', 'celebrated', 'on', 'december', '25']
A: ['christmas']
Q: ['what', 'is', 'the', 'currency', 'of', 'japan']
A: ['yen']
Q: ['how', 'many', 'legs', 'does', 'a', 'spider', 'have']
A: ['8']
Q: ['which', 'sport', 'uses', 'a', 'net,', 'ball,', 'and', 'hoop']
A: ['basketball']
Q: ['which', 'country', 'is', 'famous', 'for', 'its', 'kangaroos']
A: ['australia']
Q: ['who', 'was', 'the', 'first', 'female', 'prime', 'minister', 'of', 'the', 'uk']
A: ['margaretthatcher']
Q: ['which', 'is', 'the', 'fastest', 'land', 'animal']
A: ['cheetah']
Q: ['what', 'is', 'the', 'first', 'element', 'on', 'the', 'periodic', 'table']
A: ['hydrogen']
Q: ['what', 'is', 'the', 'capital', 'of', 'spain']
A: ['madrid']
Q: ['which', 'planet', 'is', 'the', 'closest', 'to', 'the', 'sun']
A: ['mercury']
Q: ['who', 'is', 'known', 'as', 'the', 'father', 'of', 'computers']
A: ['charlesbabbage']
Q: ['what', 'is', 'the', 'capital', 'of', 'mexico']
A: ['mexicocity']
Q: ['how', 'many', 'colors', 'are', 'in', 'a', 'rainbow']
A: ['7']
Q: ['which', 'musical', 'instrument', 'has', 'black', 'and', 'white', 'keys']
A: ['piano']
Q: ['who', 'discovered', 'the', 'americas', 'in', '1492']
A: ['christophercolumbus']
Q: ['which', 'disney', 'character', 'has', 'a', 'long', 'nose', 'and', 'grows', 'it', 'when', 'lying']
A: ['pinocchio']
Q: ['who', 'directed', 'the', 'movie', 'titanic']
A: ['jamescameron']
Q: ['which', 'superhero', 'is', 'also', 'known', 'as', 'the', 'dark', 'knight']
A: ['batman']
Q: ['what', 'is', 'the', 'capital', 'of', 'brazil']
A: ['brasilia']
Q: ['which', 'fruit', 'is', 'known', 'as', 'the', 'king', 'of', 'fruits']
A: ['mango']
Q: ['which', 'country', 'is', 'known', 'for', 'the', 'eiffel', 'tower']
A: ['france']

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [11]:
vocab

{'what': 0,
 'is': 1,
 'the': 2,
 'capital': 3,
 'of': 4,
 'france': 5,
 'paris': 6,
 'germany': 7,
 'berlin': 8,
 'who': 9,
 'wrote': 10,
 'to': 11,
 'kill': 12,
 'a': 13,
 'mockingbird': 14,
 'harper-lee': 15,
 'largest': 16,
 'planet': 17,
 'in': 18,
 'our': 19,
 'solar': 20,
 'system': 21,
 'jupiter': 22,
 'boiling': 23,
 'point': 24,
 'water': 25,
 'celsius': 26,
 '100': 27,
 'painted': 28,
 'mona': 29,
 'lisa': 30,
 'leonardo-da-vinci': 31,
 'square': 32,
 'root': 33,
 '64': 34,
 '8': 35,
 'chemical': 36,
 'symbol': 37,
 'for': 38,
 'gold': 39,
 'au': 40,
 'which': 41,
 'year': 42,
 'did': 43,
 'world': 44,
 'war': 45,
 'ii': 46,
 'end': 47,
 '1945': 48,
 'longest': 49,
 'river': 50,
 'nile': 51,
 'japan': 52,
 'tokyo': 53,
 'developed': 54,
 'theory': 55,
 'relativity': 56,
 'albert-einstein': 57,
 'freezing': 58,
 'fahrenheit': 59,
 '32': 60,
 'known': 61,
 'as': 62,
 'red': 63,
 'mars': 64,
 'author': 65,
 '1984': 66,
 'george-orwell': 67,
 'currency': 68,
 'united': 69,
 'kingdom': 70,
 'pound': 71,
 'india': 72,
 'delhi': 73,
 'discovered': 74,
 'gravity': 75,
 'newton': 76,
 'how': 77,
 'many': 78,
 'continents': 79,
 'are': 80,
 'there': 81,
 'on': 82,
 'earth': 83,
 '7': 84,
 'gas': 85,
 'do': 86,
 'plants': 87,
 'use': 88,
 'photosynthesis': 89,
 'co2': 90,
 'smallest': 91,
 'prime': 92,
 'number': 93,
 '2': 94,
 'invented': 95,
 'telephone': 96,
 'alexander-graham-bell': 97,
 'australia': 98,
 'canberra': 99,
 'ocean': 100,
 'pacific-ocean': 101,
 'speed': 102,
 'light': 103,
 'vacuum': 104,
 '299,792,458m/s': 105,
 'language': 106,
 'spoken': 107,
 'brazil': 108,
 'portuguese': 109,
 'penicillin': 110,
 'alexander-fleming': 111,
 'canada': 112,
 'ottawa': 113,
 'mammal': 114,
 'whale': 115,
 'element': 116,
 'has': 117,
 'atomic': 118,
 '1': 119,
 'hydrogen': 120,
 'tallest': 121,
 'mountain': 122,
 'everest': 123,
 'city': 124,
 'big': 125,
 'apple': 126,
 'newyork': 127,
 'planets': 128,
 'starry': 129,
 'night': 130,
 'vangogh': 131,
 'formula': 132,
 'h2o': 133,
 'italy': 134,
 'rome': 135,
 'country': 136,
 'famous': 137,
 'sushi': 138,
 'was': 139,
 'first': 140,
 'person': 141,
 'step': 142,
 'moon': 143,
 'armstrong': 144,
 'main': 145,
 'ingredient': 146,
 'guacamole': 147,
 'avocado': 148,
 'sides': 149,
 'does': 150,
 'hexagon': 151,
 'have': 152,
 '6': 153,
 'china': 154,
 'yuan': 155,
 'pride': 156,
 'and': 157,
 'prejudice': 158,
 'jane-austen': 159,
 'iron': 160,
 'fe': 161,
 'hardest': 162,
 'natural': 163,
 'substance': 164,
 'diamond': 165,
 'continent': 166,
 'by': 167,
 'area': 168,
 'asia': 169,
 'president': 170,
 'states': 171,
 'george-washington': 172,
 'bird': 173,
 'its': 174,
 'ability': 175,
 'mimic': 176,
 'sounds': 177,
 'parrot': 178,
 'longest-running': 179,
 'animated': 180,
 'tv': 181,
 'show': 182,
 'simpsons': 183,
 'vaticancity': 184,
 'most': 185,
 'moons': 186,
 'saturn': 187,
 'romeo': 188,
 'juliet': 189,
 'shakespeare': 190,
 'earths': 191,
 'atmosphere': 192,
 'nitrogen': 193,
 'bones': 194,
 'adult': 195,
 'human': 196,
 'body': 197,
 '206': 198,
 'metal': 199,
 'liquid': 200,
 'at': 201,
 'room': 202,
 'temperature': 203,
 'mercury': 204,
 'russia': 205,
 'moscow': 206,
 'electricity': 207,
 'benjamin-franklin': 208,
 'second-largest': 209,
 'land': 210,
 'color': 211,
 'ripe': 212,
 'banana': 213,
 'yellow': 214,
 'month': 215,
 '28': 216,
 'days': 217,
 'common': 218,
 'february': 219,
 'study': 220,
 'living': 221,
 'organisms': 222,
 'called': 223,
 'biology': 224,
 'home': 225,
 'great': 226,
 'wall': 227,
 'bees': 228,
 'collect': 229,
 'from': 230,
 'flowers': 231,
 'nectar': 232,
 'opposite': 233,
 'day': 234,
 'south': 235,
 'korea': 236,
 'seoul': 237,
 'bulb': 238,
 'edison': 239,
 'humans': 240,
 'breathe': 241,
 'survival': 242,
 'oxygen': 243,
 '144': 244,
 '12': 245,
 'pyramids': 246,
 'giza': 247,
 'egypt': 248,
 'sea': 249,
 'creature': 250,
 'eight': 251,
 'arms': 252,
 'octopus': 253,
 'holiday': 254,
 'celebrated': 255,
 'december': 256,
 '25': 257,
 'christmas': 258,
 'yen': 259,
 'legs': 260,
 'spider': 261,
 'sport': 262,
 'uses': 263,
 'net,': 264,
 'ball,': 265,
 'hoop': 266,
 'basketball': 267,
 'kangaroos': 268,
 'female': 269,
 'minister': 270,
 'uk': 271,
 'margaretthatcher': 272,
 'fastest': 273,
 'animal': 274,
 'cheetah': 275,
 'periodic': 276,
 'table': 277,
 'spain': 278,
 'madrid': 279,
 'closest': 280,
 'sun': 281,
 'father': 282,
 'computers': 283,
 'charlesbabbage': 284,
 'mexico': 285,
 'mexicocity': 286,
 'colors': 287,
 'rainbow': 288,
 'musical': 289,
 'instrument': 290,
 'black': 291,
 'white': 292,
 'keys': 293,
 'piano': 294,
 'americas': 295,
 '1492': 296,
 'christophercolumbus': 297,
 'disney': 298,
 'character': 299,
 'long': 300,
 'nose': 301,
 'grows': 302,
 'it': 303,
 'when': 304,
 'lying': 305,
 'pinocchio': 306,
 'directed': 307,
 'movie': 308,
 'titanic': 309,
 'jamescameron': 310,
 'superhero': 311,
 'also': 312,
 'dark': 313,
 'knight': 314,
 'batman': 315,
 'brasilia': 316,
 'fruit': 317,
 'king': 318,
 'fruits': 319,
 'mango': 320,
 'eiffel': 321,
 'tower': 322}

In [12]:
def text_to_indices(text, vocab):
  indexed_text = []
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])
  return indexed_text

In [13]:
text_to_indices('what is the capital of france?', vocab)

[0, 1, 2, 3, 4, 5]

In [14]:
vocab

{'what': 0,
 'is': 1,
 'the': 2,
 'capital': 3,
 'of': 4,
 'france': 5,
 'paris': 6,
 'germany': 7,
 'berlin': 8,
 'who': 9,
 'wrote': 10,
 'to': 11,
 'kill': 12,
 'a': 13,
 'mockingbird': 14,
 'harper-lee': 15,
 'largest': 16,
 'planet': 17,
 'in': 18,
 'our': 19,
 'solar': 20,
 'system': 21,
 'jupiter': 22,
 'boiling': 23,
 'point': 24,
 'water': 25,
 'celsius': 26,
 '100': 27,
 'painted': 28,
 'mona': 29,
 'lisa': 30,
 'leonardo-da-vinci': 31,
 'square': 32,
 'root': 33,
 '64': 34,
 '8': 35,
 'chemical': 36,
 'symbol': 37,
 'for': 38,
 'gold': 39,
 'au': 40,
 'which': 41,
 'year': 42,
 'did': 43,
 'world': 44,
 'war': 45,
 'ii': 46,
 'end': 47,
 '1945': 48,
 'longest': 49,
 'river': 50,
 'nile': 51,
 'japan': 52,
 'tokyo': 53,
 'developed': 54,
 'theory': 55,
 'relativity': 56,
 'albert-einstein': 57,
 'freezing': 58,
 'fahrenheit': 59,
 '32': 60,
 'known': 61,
 'as': 62,
 'red': 63,
 'mars': 64,
 'author': 65,
 '1984': 66,
 'george-orwell': 67,
 'currency': 68,
 'united': 69,
 'kingdom': 70,
 'pound': 71,
 'india': 72,
 'delhi': 73,
 'discovered': 74,
 'gravity': 75,
 'newton': 76,
 'how': 77,
 'many': 78,
 'continents': 79,
 'are': 80,
 'there': 81,
 'on': 82,
 'earth': 83,
 '7': 84,
 'gas': 85,
 'do': 86,
 'plants': 87,
 'use': 88,
 'photosynthesis': 89,
 'co2': 90,
 'smallest': 91,
 'prime': 92,
 'number': 93,
 '2': 94,
 'invented': 95,
 'telephone': 96,
 'alexander-graham-bell': 97,
 'australia': 98,
 'canberra': 99,
 'ocean': 100,
 'pacific-ocean': 101,
 'speed': 102,
 'light': 103,
 'vacuum': 104,
 '299,792,458m/s': 105,
 'language': 106,
 'spoken': 107,
 'brazil': 108,
 'portuguese': 109,
 'penicillin': 110,
 'alexander-fleming': 111,
 'canada': 112,
 'ottawa': 113,
 'mammal': 114,
 'whale': 115,
 'element': 116,
 'has': 117,
 'atomic': 118,
 '1': 119,
 'hydrogen': 120,
 'tallest': 121,
 'mountain': 122,
 'everest': 123,
 'city': 124,
 'big': 125,
 'apple': 126,
 'newyork': 127,
 'planets': 128,
 'starry': 129,
 'night': 130,
 'vangogh': 131,
 'formula': 132,
 'h2o': 133,
 'italy': 134,
 'rome': 135,
 'country': 136,
 'famous': 137,
 'sushi': 138,
 'was': 139,
 'first': 140,
 'person': 141,
 'step': 142,
 'moon': 143,
 'armstrong': 144,
 'main': 145,
 'ingredient': 146,
 'guacamole': 147,
 'avocado': 148,
 'sides': 149,
 'does': 150,
 'hexagon': 151,
 'have': 152,
 '6': 153,
 'china': 154,
 'yuan': 155,
 'pride': 156,
 'and': 157,
 'prejudice': 158,
 'jane-austen': 159,
 'iron': 160,
 'fe': 161,
 'hardest': 162,
 'natural': 163,
 'substance': 164,
 'diamond': 165,
 'continent': 166,
 'by': 167,
 'area': 168,
 'asia': 169,
 'president': 170,
 'states': 171,
 'george-washington': 172,
 'bird': 173,
 'its': 174,
 'ability': 175,
 'mimic': 176,
 'sounds': 177,
 'parrot': 178,
 'longest-running': 179,
 'animated': 180,
 'tv': 181,
 'show': 182,
 'simpsons': 183,
 'vaticancity': 184,
 'most': 185,
 'moons': 186,
 'saturn': 187,
 'romeo': 188,
 'juliet': 189,
 'shakespeare': 190,
 'earths': 191,
 'atmosphere': 192,
 'nitrogen': 193,
 'bones': 194,
 'adult': 195,
 'human': 196,
 'body': 197,
 '206': 198,
 'metal': 199,
 'liquid': 200,
 'at': 201,
 'room': 202,
 'temperature': 203,
 'mercury': 204,
 'russia': 205,
 'moscow': 206,
 'electricity': 207,
 'benjamin-franklin': 208,
 'second-largest': 209,
 'land': 210,
 'color': 211,
 'ripe': 212,
 'banana': 213,
 'yellow': 214,
 'month': 215,
 '28': 216,
 'days': 217,
 'common': 218,
 'february': 219,
 'study': 220,
 'living': 221,
 'organisms': 222,
 'called': 223,
 'biology': 224,
 'home': 225,
 'great': 226,
 'wall': 227,
 'bees': 228,
 'collect': 229,
 'from': 230,
 'flowers': 231,
 'nectar': 232,
 'opposite': 233,
 'day': 234,
 'south': 235,
 'korea': 236,
 'seoul': 237,
 'bulb': 238,
 'edison': 239,
 'humans': 240,
 'breathe': 241,
 'survival': 242,
 'oxygen': 243,
 '144': 244,
 '12': 245,
 'pyramids': 246,
 'giza': 247,
 'egypt': 248,
 'sea': 249,
 'creature': 250,
 'eight': 251,
 'arms': 252,
 'octopus': 253,
 'holiday': 254,
 'celebrated': 255,
 'december': 256,
 '25': 257,
 'christmas': 258,
 'yen': 259,
 'legs': 260,
 'spider': 261,
 'sport': 262,
 'uses': 263,
 'net,': 264,
 'ball,': 265,
 'hoop': 266,
 'basketball': 267,
 'kangaroos': 268,
 'female': 269,
 'minister': 270,
 'uk': 271,
 'margaretthatcher': 272,
 'fastest': 273,
 'animal': 274,
 'cheetah': 275,
 'periodic': 276,
 'table': 277,
 'spain': 278,
 'madrid': 279,
 'closest': 280,
 'sun': 281,
 'father': 282,
 'computers': 283,
 'charlesbabbage': 284,
 'mexico': 285,
 'mexicocity': 286,
 'colors': 287,
 'rainbow': 288,
 'musical': 289,
 'instrument': 290,
 'black': 291,
 'white': 292,
 'keys': 293,
 'piano': 294,
 'americas': 295,
 '1492': 296,
 'christophercolumbus': 297,
 'disney': 298,
 'character': 299,
 'long': 300,
 'nose': 301,
 'grows': 302,
 'it': 303,
 'when': 304,
 'lying': 305,
 'pinocchio': 306,
 'directed': 307,
 'movie': 308,
 'titanic': 309,
 'jamescameron': 310,
 'superhero': 311,
 'also': 312,
 'dark': 313,
 'knight': 314,
 'batman': 315,
 'brasilia': 316,
 'fruit': 317,
 'king': 318,
 'fruits': 319,
 'mango': 320,
 'eiffel': 321,
 'tower': 322}

In [15]:
class QADataset(Dataset):
  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab
  def __len__(self):
    return self.df.shape[0]
  def __getitem__(self, index):
    numerical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)
    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [16]:
dataset = QADataset(df, vocab)

In [17]:
dataloader = DataLoader(dataset, batch_size = 1, shuffle = True)

In [18]:
for q,a in dataloader:
  print(q,a)

tensor([[ 77,  78, 149, 150,  13, 151, 152]]) tensor([[153]])
tensor([[ 41,  17, 117,   2, 185, 186]]) tensor([[187]])
tensor([[  0,   1,   2,   3,   4, 108]]) tensor([[316]])
tensor([[  9,  10, 156, 157, 158]]) tensor([[159]])
tensor([[ 41, 116, 117,   2, 118,  93, 119]]) tensor([[120]])
tensor([[ 41, 215, 117, 216, 217,  18,  13, 218,  42]]) tensor([[219]])
tensor([[  0,   1,   2,  36, 132,   4,  25]]) tensor([[133]])
tensor([[ 41, 136,   1, 137,  38, 138]]) tensor([[52]])
tensor([[0, 1, 2, 3, 4, 5]]) tensor([[6]])
tensor([[  0,   1,   2,   3,   4, 134]]) tensor([[135]])
tensor([[  0,   1,   2, 179, 180, 181, 182]]) tensor([[183]])
tensor([[ 41, 173,   1,  61,  38, 174, 175,  11, 176, 177]]) tensor([[178]])
tensor([[ 77,  78, 287,  80,  18,  13, 288]]) tensor([[84]])
tensor([[  0,   1,   2,   3,   4, 285]]) tensor([[286]])
tensor([[ 77,  78, 194,  80,  18,   2, 195, 196, 197]]) tensor([[198]])
tensor([[  9, 139,   2, 140, 269,  92, 270,   4,   2, 271]]) tensor([[272]])
tensor([[  0,   1,   2,  16, 114,  82,  83]]) tensor([[115]])
tensor([[ 41, 100,   1,   2,  16]]) tensor([[101]])
tensor([[ 41, 136,   1, 137,  38, 174, 268]]) tensor([[98]])
tensor([[ 0,  1,  2, 58, 24,  4, 25, 18, 59]]) tensor([[60]])
tensor([[ 41, 136,   1, 225,  11,   2, 226, 227]]) tensor([[154]])
tensor([[ 0,  1,  2, 32, 33,  4, 34]]) tensor([[35]])
tensor([[  0,   1,   2,   3,   4, 235, 236]]) tensor([[237]])
tensor([[  0,  86, 228, 229, 230, 231]]) tensor([[232]])
tensor([[  9,  95,   2, 103, 238]]) tensor([[239]])
tensor([[  0,   1,   2,  32,  33,   4, 244]]) tensor([[245]])
tensor([[  0,   1,   2, 220,   4, 221, 222, 223]]) tensor([[224]])
tensor([[ 9, 74, 75]]) tensor([[76]])
tensor([[ 41, 136,   1,  61,  38,   2, 321, 322]]) tensor([[5]])
tensor([[  9,  74, 110]]) tensor([[111]])
tensor([[ 0,  1,  2,  3,  4, 52]]) tensor([[53]])
tensor([[ 41, 166,   1,   2,  16, 167, 168]]) tensor([[169]])
tensor([[  9,   1,  61,  62,   2, 282,   4, 283]]) tensor([[284]])
tensor([[ 0,  1,  2,  3,  4, 98]]) tensor([[99]])
tensor([[  0,   1,   2,   3,   4, 112]]) tensor([[113]])
tensor([[ 77,  78, 128,  80,  18,   2,  20,  21]]) tensor([[35]])
tensor([[ 9, 54,  2, 55,  4, 56]]) tensor([[57]])
tensor([[  0,   1,   2, 102,   4, 103,  18, 104]]) tensor([[105]])
tensor([[  0,   1,   2,  36,  37,  38, 160]]) tensor([[161]])
tensor([[ 0,  1,  2, 16, 17, 18, 19, 20, 21]]) tensor([[22]])
tensor([[  0,   1,   2,  68,   4, 154]]) tensor([[155]])
tensor([[ 41, 199,   1,  13, 200, 201, 202, 203]]) tensor([[204]])
tensor([[  0,   1,   2, 211,   4,  13, 212, 213]]) tensor([[214]])
tensor([[ 41, 254,   1, 255,  82, 256, 257]]) tensor([[258]])
tensor([[ 41,   1,   2, 209, 136, 167, 210, 168]]) tensor([[112]])
tensor([[  9,  28, 129, 130]]) tensor([[131]])
tensor([[ 0,  1,  2, 91, 92, 93]]) tensor([[94]])
tensor([[  0,   1,   2, 145, 146,  18, 147]]) tensor([[148]])
tensor([[ 41, 317,   1,  61,  62,   2, 318,   4, 319]]) tensor([[320]])
tensor([[41, 42, 43, 44, 45, 46, 47]]) tensor([[48]])
tensor([[  0,   1,   2, 233,   4, 234]]) tensor([[130]])
tensor([[ 0,  1,  2, 68,  4,  2, 69, 70]]) tensor([[71]])
tensor([[ 0,  1,  2, 68,  4, 52]]) tensor([[259]])
tensor([[  0,   1,   2,   3,   4, 278]]) tensor([[279]])
tensor([[  9, 307,   2, 308, 309]]) tensor([[310]])
tensor([[ 41,   1,   2, 273, 210, 274]]) tensor([[275]])
tensor([[ 41,  17,   1,   2, 280,  11,   2, 281]]) tensor([[204]])
tensor([[ 9, 95,  2, 96]]) tensor([[97]])
tensor([[  0,   1,   2, 121, 122,  18,   2,  44]]) tensor([[123]])
tensor([[  9,  10, 188, 157, 189]]) tensor([[190]])
tensor([[ 9, 28,  2, 29, 30]]) tensor([[31]])
tensor([[  9, 139,   2, 140, 170,   4,   2,  69, 171]]) tensor([[172]])
tensor([[ 0,  1,  2, 36, 37, 38, 39]]) tensor([[40]])
tensor([[ 41, 136, 117,   2, 246,   4, 247]]) tensor([[248]])
tensor([[ 77,  78, 260, 150,  13, 261, 152]]) tensor([[35]])
tensor([[ 0,  1,  2, 49, 50, 18,  2, 44]]) tensor([[51]])
tensor([[ 41, 262, 263,  13, 264, 265, 157, 266]]) tensor([[267]])
tensor([[ 0,  1,  2,  3,  4, 72]]) tensor([[73]])
tensor([[ 41, 249, 250, 117, 251, 252]]) tensor([[253]])
tensor([[77, 78, 79, 80, 81, 82, 83]]) tensor([[84]])
tensor([[41, 17,  1, 61, 62,  2, 63, 17]]) tensor([[64]])
tensor([[ 41, 106,   1, 107,  18, 108]]) tensor([[109]])
tensor([[ 41, 298, 299, 117,  13, 300, 301, 157, 302, 303, 304, 305]]) tensor([[306]])
tensor([[0, 1, 2, 3, 4, 7]]) tensor([[8]])
tensor([[  0,   1,   2, 145,  85,  18, 191, 192]]) tensor([[193]])
tensor([[ 9, 10, 11, 12, 13, 14]]) tensor([[15]])
tensor([[ 41, 124,   1,  61,  62,   2, 125, 126]]) tensor([[127]])
tensor([[  0,   1,   2,  91, 136,  18,   2,  44]]) tensor([[184]])
tensor([[ 41,  85,  86, 240, 241,  18,  38, 242]]) tensor([[243]])
tensor([[ 9,  1,  2, 65,  4, 66]]) tensor([[67]])
tensor([[  9,  74, 207]]) tensor([[208]])
tensor([[  0,   1,   2,   3,   4, 205]]) tensor([[206]])
tensor([[ 41, 289, 290, 117, 291, 157, 292, 293]]) tensor([[294]])
tensor([[  9, 139,   2, 140, 141,  11, 142,  82,   2, 143]]) tensor([[144]])
tensor([[ 0,  1,  2, 23, 24,  4, 25, 18, 26]]) tensor([[27]])
tensor([[  0,   1,   2, 162, 163, 164,  82,  83]]) tensor([[165]])
tensor([[  0,   1,   2, 140, 116,  82,   2, 276, 277]]) tensor([[120]])
tensor([[  9,  74,   2, 295,  18, 296]]) tensor([[297]])
tensor([[41, 85, 86, 87, 88, 38, 89]]) tensor([[90]])
tensor([[ 41, 311,   1, 312,  61,  62,   2, 313, 314]]) tensor([[315]])

In [19]:
import torch.nn as nn
class nnRNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 50)
    self.rnn = nn.RNN(50, 64, batch_first=True) # Add batch_first=True
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, x):
    x = self.embedding(x) # x: (batch_size, seq_len_q, embedding_dim)

    # output: (batch_size, seq_len_q, hidden_size)
    # h: (num_layers * num_directions, batch_size, hidden_size)
    # For a simple RNN, h is the final hidden state for each element in the batch.
    _, h = self.rnn(x) # We only need the last hidden state h

    # For a single-layer, uni-directional RNN, h will have shape (1, batch_size, hidden_size).
    # We need to squeeze out the first dimension (num_layers) to get (batch_size, hidden_size)
    # to feed into the linear layer.
    x = self.fc(h.squeeze(0)) # x: (batch_size, vocab_size)
    return x

In [20]:
learning_rate = 0.01
epochs = 20

In [21]:
model = nnRNN(len(vocab))

In [22]:
criteria = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [23]:
for epoch in range(epochs):
  total_loss = 0
  for q, a in dataloader:
    optimizer.zero_grad()
    output = model(q)
    # Squeeze the target 'a' to (batch_size,) as expected by CrossEntropyLoss
    loss = criteria(output, a.squeeze(1))
    loss.backward()
    optimizer.step()
    total_loss = total_loss + loss.item()
  print(f'epoch: {epoch+1}, loss: {total_loss:4f}')

epoch: 1, loss: 539.505683
epoch: 2, loss: 318.609594
epoch: 3, loss: 160.854129
epoch: 4, loss: 61.386023
epoch: 5, loss: 32.615368
epoch: 6, loss: 18.016381
epoch: 7, loss: 15.873919
epoch: 8, loss: 10.148080
epoch: 9, loss: 14.069743
epoch: 10, loss: 10.775402
epoch: 11, loss: 8.145693
epoch: 12, loss: 14.029299
epoch: 13, loss: 9.338275
epoch: 14, loss: 15.316695
epoch: 15, loss: 16.041831
epoch: 16, loss: 10.630182
epoch: 17, loss: 8.950038
epoch: 18, loss: 15.118300
epoch: 19, loss: 39.467816
epoch: 20, loss: 29.620271

In [24]:
total = 0
correct = 0
with torch.no_grad():
  for batch_features, batch_labels in dataloader:
    y_pred = model(batch_features)
    _, predicted = torch.max(y_pred, 1)
    total += batch_labels.size(0) # shape[0] will also work the same.
    correct += (predicted == batch_labels).sum().item()
accuracy = correct / total
print(accuracy)

0.9222222222222223

In [25]:
def predict(model, question, threshold = 0.5):
  numerical_question = text_to_indices(question, vocab)
  numerical_question = torch.tensor(numerical_question).unsqueeze(0)

  # Get raw logits from the model
  logits = model(numerical_question)

  # Apply softmax to get probabilities
  probs = torch.softmax(logits, dim=1)

  # Get the predicted class index and its probability
  value, item = torch.max(probs, dim=1)

  # Check against threshold
  if value < threshold:
    return "I don't know"

  # Find the word corresponding to the predicted index
  predicted_index = item.item() # Get the scalar index

  # Invert the vocab dictionary to map indices back to words
  idx_to_word = {idx: word for word, idx in vocab.items()}

  try:
    predicted_word = idx_to_word[predicted_index]
    return predicted_word
  except KeyError:
    return "Predicted index not found in vocab"

In [26]:
predict(model, "What is the boiling point of water in Celsius?")

'100'

In [27]:
output.shape

torch.Size([1, 323])

In [28]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)

In [29]:
import nltk
import torch
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [30]:
document = """
Over centuries, the Bhagavad Gita has been considered animportant spiritual guidebook and has influenced many thought leaders inhuman history. The Gita is a conversational poem and is part of the greatIndian epic the Mahabharata, which is a story about the families of twobrothers who inherit a kingdom from their father. These cousins are knownas the ‘Pandavas’ and the ‘Kauravas’. The Kaurava brothers are 100 innumber and the Pandavas are 5. The Kauravas, not wanting to share thekingdom with their cousins, invite them to a game of dice. They usedubious means to defeat the Pandavas and annex their kingdom afterwinning the wager. As per the rules of the wager, the Pandavas completetheir stay outside the kingdom and come back to ask for their fair share ofthe kingdom so that they can rule with dignity. The Kauravas refuse tohonor the agreement and even deny the Pandavas a settlement of 5 villagesso that they can live in peace. As the Kauravas refuse to budge even aninch, the Pandavas have no choice but to declare war on them to get backtheir share of the kingdom. During this period, The Lord who hasincarnated as Krishna offers the cousins a choice between His army andHimself. But He makes it clear that He Himself would not be participatingin the war. The Kauravas choose His army as Krishna would not befighting, and the Pandavas are happy to just have Krishna on their side.Krishna takes on the role of charioteer to Arjuna’s chariot (Arjuna is thethird brother among the five Pandavas).Before the war starts, the two armies assemble on the battlefield,facing each other. At this point, Arjuna requests Krishna to place hischariot in the middle so that he can get a full view of the warring forces.Since this is a war between cousins, Arjuna sees his cousins, uncles,grandfathers, great grandfathers, nephews, friends, classmates etc. on bothsides. He is overcome with emotion and grief at the prospect of bloodshedamong his family and friends for the sake of a kingdom. He declares hisintention to renounce the war and let the Kauravas keep the kingdom, thus abdicating his responsibility as a prince and a warrior. It is at this stage thatKrishna teaches him the Gita which is structured as a series of questionsfrom Arjuna and answers from Krishna. Krishna extols the virtue ofperforming one’s duties regardless of the outcome, and not avoidingprescribed duties which may be difficult and unpleasant. As Krishna startsto talk to Arjuna on the virtues of doing one’s work (in this case Arjunaneeding to fight a rightful war), Arjuna asks a series of questions on thebigger issues of life, individual souls, the Lord Almighty, the universe, thecircle of life etc., for which Krishna provides clear, unambiguous answers.He finally convinces Arjuna that his fears were unfounded and that heshould fight to free the Kingdom from the Kauravas and provide a just andcompassionate administration to his citizens.At first a battleground is hardly the place for someone to bepreaching philosophy. However, many of the questions that we have in lifeare about the choices we have to make, especially in challenging times. It isinteresting to note that Sanskrit verses lend themselves to multiplemeanings and in one interpretation, the battleground in the Gita iscompared to the human body (and mind), and the battle between thePandavas and the Kauravas is compared to the constant strife between goodand evil thoughts that we encounter daily. The Gita is indeed a teaching forall of us, with Arjuna acting as an example of an individual at crossroads,desperately looking for guidance and support.The Gita is one of the most widely read and commented uponspiritual works in human history. There are several excellent books on it invarious languages. Given that the original work is in Sanskrit, most of thescholarly commentaries have been in Sanskrit or other Indian languageswhich are closer to Sanskrit. To read and comprehend many of them, onewould need some training in Indian spiritual studies, as many of themliberally use Sanskrit words albeit transliterated in English. It was felt thatthere is a need to present the key concepts of The Gita in plain English foreveryday folk, minimizing the use of Sanskrit words. These observationsled to the development of this manuscript. While there are many learned commentaries on the Gita written overthe centuries, this author has been greatly influenced by the authoritativecommentary and lucid explanations of difficult concepts by SriMadhwacharya, the 12th century ascetic who propounded the philosophy ofdualistic theism (concept of difference between the almighty Lord andindividual souls at all times and places). Sri Madhwacharya’s commentaryhas been further elaborated and summarized by later day savants such asSri Padmanabha Teertha (13th Century), Sri Jaya Teertha (13th Century) SriVadiraja Teertha (16th Century), Sri Raghavendra Teertha (17th century)and others.The Gita consists of 18 chapters with a total of 7011 verses inSanskrit. The Gita is part of the great Hindu epic The Mahabharata andappears as Chapters 25 to 42, in the Book of Bheeshma in theMahabharata. Most of the verses appear in the anushtap meter, whereeach verse has a total of 32 letters with 8 words in each of the fourquadrants. Some verses in the 15th chapter appear in trishtup meter with 44words. As per Sri Raghavendra Teertha [GV], the 18 chapters can bebroadly classified into 3 sections with 6 chapters in each section. The firstsection with chapters 1-6 (280 verses) broadly outlines how one can obtaindivine, spiritual knowledge (jnana upaya), the second section with chapters7-12 (209 verses) focuses on devotion and divine, spiritual knowledge(vijnana) that leads one to liberation, and the third section consisting ofchapters 13-18 (212 verses) elaborates on the concepts in the first twosections. It is also believed that the Gita conveys at least 10 differentmeanings, all of which are consistent with one another. An illustration ofmultiple meanings in the Gita will appear in Chapter 2. It is also said thatthe Gita has 3 major interpretations – historical, psychological, and spiritual. Numbers and numerology play an incredibly significant role inIndian theology. In fact, the study of knowledge is termed ‘Sankhya Yoga’,with Sankhya meaning ‘arithmetic’. The world around us is based onnumbers. We are constantly measuring, managing, quantifying all ouractivities with the aid of numbers. We wake up at a certain time, wework/study for certain hours, we travel a certain distance, we consumesome amount of food, we transact with certain currency, we performactivities at a certain time, on a certain day, in a certain month, in a certainyear etc. And all these numbers and calculations are based on the positionand movement of celestial objects such as the Sun, Moon, stars etc."""

In [31]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [32]:
tokens = word_tokenize(document.lower())
tokens

['over',
 'centuries',
 ',',
 'the',
 'bhagavad',
 'gita',
 'has',
 'been',
 'considered',
 'animportant',
 'spiritual',
 'guidebook',
 'and',
 'has',
 'influenced',
 'many',
 'thought',
 'leaders',
 'inhuman',
 'history',
 '.',
 'the',
 'gita',
 'is',
 'a',
 'conversational',
 'poem',
 'and',
 'is',
 'part',
 'of',
 'the',
 'greatindian',
 'epic',
 'the',
 'mahabharata',
 ',',
 'which',
 'is',
 'a',
 'story',
 'about',
 'the',
 'families',
 'of',
 'twobrothers',
 'who',
 'inherit',
 'a',
 'kingdom',
 'from',
 'their',
 'father',
 '.',
 'these',
 'cousins',
 'are',
 'knownas',
 'the',
 '‘',
 'pandavas',
 '’',
 'and',
 'the',
 '‘',
 'kauravas',
 '’',
 '.',
 'the',
 'kaurava',
 'brothers',
 'are',
 '100',
 'innumber',
 'and',
 'the',
 'pandavas',
 'are',
 '5.',
 'the',
 'kauravas',
 ',',
 'not',
 'wanting',
 'to',
 'share',
 'thekingdom',
 'with',
 'their',
 'cousins',
 ',',
 'invite',
 'them',
 'to',
 'a',
 'game',
 'of',
 'dice',
 '.',
 'they',
 'usedubious',
 'means',
 'to',
 'defeat',
 'the',
 'pandavas',
 'and',
 'annex',
 'their',
 'kingdom',
 'afterwinning',
 'the',
 'wager',
 '.',
 'as',
 'per',
 'the',
 'rules',
 'of',
 'the',
 'wager',
 ',',
 'the',
 'pandavas',
 'completetheir',
 'stay',
 'outside',
 'the',
 'kingdom',
 'and',
 'come',
 'back',
 'to',
 'ask',
 'for',
 'their',
 'fair',
 'share',
 'ofthe',
 'kingdom',
 'so',
 'that',
 'they',
 'can',
 'rule',
 'with',
 'dignity',
 '.',
 'the',
 'kauravas',
 'refuse',
 'tohonor',
 'the',
 'agreement',
 'and',
 'even',
 'deny',
 'the',
 'pandavas',
 'a',
 'settlement',
 'of',
 '5',
 'villagesso',
 'that',
 'they',
 'can',
 'live',
 'in',
 'peace',
 '.',
 'as',
 'the',
 'kauravas',
 'refuse',
 'to',
 'budge',
 'even',
 'aninch',
 ',',
 'the',
 'pandavas',
 'have',
 'no',
 'choice',
 'but',
 'to',
 'declare',
 'war',
 'on',
 'them',
 'to',
 'get',
 'backtheir',
 'share',
 'of',
 'the',
 'kingdom',
 '.',
 'during',
 'this',
 'period',
 ',',
 'the',
 'lord',
 'who',
 'hasincarnated',
 'as',
 'krishna',
 'offers',
 'the',
 'cousins',
 'a',
 'choice',
 'between',
 'his',
 'army',
 'andhimself',
 '.',
 'but',
 'he',
 'makes',
 'it',
 'clear',
 'that',
 'he',
 'himself',
 'would',
 'not',
 'be',
 'participatingin',
 'the',
 'war',
 '.',
 'the',
 'kauravas',
 'choose',
 'his',
 'army',
 'as',
 'krishna',
 'would',
 'not',
 'befighting',
 ',',
 'and',
 'the',
 'pandavas',
 'are',
 'happy',
 'to',
 'just',
 'have',
 'krishna',
 'on',
 'their',
 'side.krishna',
 'takes',
 'on',
 'the',
 'role',
 'of',
 'charioteer',
 'to',
 'arjuna',
 '’',
 's',
 'chariot',
 '(',
 'arjuna',
 'is',
 'thethird',
 'brother',
 'among',
 'the',
 'five',
 'pandavas',
 ')',
 '.before',
 'the',
 'war',
 'starts',
 ',',
 'the',
 'two',
 'armies',
 'assemble',
 'on',
 'the',
 'battlefield',
 ',',
 'facing',
 'each',
 'other',
 '.',
 'at',
 'this',
 'point',
 ',',
 'arjuna',
 'requests',
 'krishna',
 'to',
 'place',
 'hischariot',
 'in',
 'the',
 'middle',
 'so',
 'that',
 'he',
 'can',
 'get',
 'a',
 'full',
 'view',
 'of',
 'the',
 'warring',
 'forces.since',
 'this',
 'is',
 'a',
 'war',
 'between',
 'cousins',
 ',',
 'arjuna',
 'sees',
 'his',
 'cousins',
 ',',
 'uncles',
 ',',
 'grandfathers',
 ',',
 'great',
 'grandfathers',
 ',',
 'nephews',
 ',',
 'friends',
 ',',
 'classmates',
 'etc',
 '.',
 'on',
 'bothsides',
 '.',
 'he',
 'is',
 'overcome',
 'with',
 'emotion',
 'and',
 'grief',
 'at',
 'the',
 'prospect',
 'of',
 'bloodshedamong',
 'his',
 'family',
 'and',
 'friends',
 'for',
 'the',
 'sake',
 'of',
 'a',
 'kingdom',
 '.',
 'he',
 'declares',
 'hisintention',
 'to',
 'renounce',
 'the',
 'war',
 'and',
 'let',
 'the',
 'kauravas',
 'keep',
 'the',
 'kingdom',
 ',',
 'thus',
 'abdicating',
 'his',
 'responsibility',
 'as',
 'a',
 'prince',
 'and',
 'a',
 'warrior',
 '.',
 'it',
 'is',
 'at',
 'this',
 'stage',
 'thatkrishna',
 'teaches',
 'him',
 'the',
 'gita',
 'which',
 'is',
 'structured',
 'as',
 'a',
 'series',
 'of',
 'questionsfrom',
 'arjuna',
 'and',
 'answers',
 'from',
 'krishna',
 '.',
 'krishna',
 'extols',
 'the',
 'virtue',
 'ofperforming',
 'one',
 '’',
 's',
 'duties',
 'regardless',
 'of',
 'the',
 'outcome',
 ',',
 'and',
 'not',
 'avoidingprescribed',
 'duties',
 'which',
 'may',
 'be',
 'difficult',
 'and',
 'unpleasant',
 '.',
 'as',
 'krishna',
 'startsto',
 'talk',
 'to',
 'arjuna',
 'on',
 'the',
 'virtues',
 'of',
 'doing',
 'one',
 '’',
 's',
 'work',
 '(',
 'in',
 'this',
 'case',
 'arjunaneeding',
 'to',
 'fight',
 'a',
 'rightful',
 'war',
 ')',
 ',',
 'arjuna',
 'asks',
 'a',
 'series',
 'of',
 'questions',
 'on',
 'thebigger',
 'issues',
 'of',
 'life',
 ',',
 'individual',
 'souls',
 ',',
 'the',
 'lord',
 'almighty',
 ',',
 'the',
 'universe',
 ',',
 'thecircle',
 'of',
 'life',
 'etc.',
 ',',
 'for',
 'which',
 'krishna',
 'provides',
 'clear',
 ',',
 'unambiguous',
 'answers.he',
 'finally',
 'convinces',
 'arjuna',
 'that',
 'his',
 'fears',
 'were',
 'unfounded',
 'and',
 'that',
 'heshould',
 'fight',
 'to',
 'free',
 'the',
 'kingdom',
 'from',
 'the',
 'kauravas',
 'and',
 'provide',
 'a',
 'just',
 'andcompassionate',
 'administration',
 'to',
 'his',
 'citizens.at',
 'first',
 'a',
 'battleground',
 'is',
 'hardly',
 'the',
 'place',
 'for',
 'someone',
 'to',
 'bepreaching',
 'philosophy',
 '.',
 'however',
 ',',
 'many',
 'of',
 'the',
 'questions',
 'that',
 'we',
 'have',
 'in',
 'lifeare',
 'about',
 'the',
 'choices',
 'we',
 'have',
 'to',
 'make',
 ',',
 'especially',
 'in',
 'challenging',
 'times',
 '.',
 'it',
 'isinteresting',
 'to',
 'note',
 'that',
 'sanskrit',
 'verses',
 'lend',
 'themselves',
 'to',
 'multiplemeanings',
 'and',
 'in',
 'one',
 'interpretation',
 ',',
 'the',
 'battleground',
 'in',
 'the',
 'gita',
 'iscompared',
 'to',
 'the',
 'human',
 'body',
 '(',
 'and',
 'mind',
 ')',
 ',',
 'and',
 'the',
 'battle',
 'between',
 'thepandavas',
 'and',
 'the',
 'kauravas',
 'is',
 'compared',
 'to',
 'the',
 'constant',
 'strife',
 'between',
 'goodand',
 'evil',
 'thoughts',
 'that',
 'we',
 'encounter',
 'daily',
 '.',
 'the',
 'gita',
 'is',
 'indeed',
 'a',
 'teaching',
 'forall',
 'of',
 'us',
 ',',
 'with',
 'arjuna',
 'acting',
 'as',
 'an',
 'example',
 'of',
 'an',
 'individual',
 'at',
 'crossroads',
 ',',
 'desperately',
 'looking',
 'for',
 'guidance',
 'and',
 'support.the',
 'gita',
 'is',
 'one',
 'of',
 'the',
 'most',
 'widely',
 'read',
 'and',
 'commented',
 'uponspiritual',
 'works',
 'in',
 'human',
 'history',
 '.',
 'there',
 'are',
 'several',
 'excellent',
 'books',
 'on',
 'it',
 'invarious',
 'languages',
 '.',
 'given',
 'that',
 'the',
 'original',
 'work',
 'is',
 'in',
 'sanskrit',
 ',',
 'most',
 'of',
 'thescholarly',
 'commentaries',
 'have',
 'been',
 'in',
 'sanskrit',
 'or',
 'other',
 'indian',
 'languageswhich',
 'are',
 'closer',
 'to',
 'sanskrit',
 '.',
 'to',
 'read',
 'and',
 'comprehend',
 'many',
 'of',
 'them',
 ',',
 'onewould',
 'need',
 'some',
 'training',
 'in',
 'indian',
 'spiritual',
 'studies',
 ',',
 'as',
 'many',
 'of',
 'themliberally',
 'use',
 'sanskrit',
 'words',
 'albeit',
 'transliterated',
 'in',
 'english',
 '.',
 'it',
 'was',
 'felt',
 'thatthere',
 'is',
 'a',
 'need',
 'to',
 'present',
 'the',
 'key',
 'concepts',
 'of',
 'the',
 'gita',
 'in',
 'plain',
 'english',
 'foreveryday',
 'folk',
 ',',
 'minimizing',
 'the',
 'use',
 'of',
 'sanskrit',
 'words',
 '.',
 'these',
 'observationsled',
 'to',
 'the',
 'development',
 'of',
 'this',
 'manuscript',
 '.',
 'while',
 'there',
 'are',
 'many',
 'learned',
 'commentaries',
 'on',
 'the',
 'gita',
 'written',
 'overthe',
 'centuries',
 ',',
 'this',
 'author',
 'has',
 'been',
 'greatly',
 'influenced',
 'by',
 'the',
 'authoritativecommentary',
 'and',
 'lucid',
 'explanations',
 'of',
 'difficult',
 'concepts',
 'by',
 'srimadhwacharya',
 ',',
 'the',
 '12th',
 'century',
 'ascetic',
 'who',
 'propounded',
 'the',
 'philosophy',
 'ofdualistic',
 'theism',
 '(',
 'concept',
 'of',
 'difference',
 'between',
 'the',
 'almighty',
 'lord',
 'andindividual',
 'souls',
 'at',
 'all',
 'times',
 'and',
 'places',
 ')',
 '.',
 'sri',
 'madhwacharya',
 '’',
 's',
 'commentaryhas',
 'been',
 'further',
 'elaborated',
 'and',
 'summarized',
 'by',
 'later',
 'day',
 'savants',
 'such',
 'assri',
 'padmanabha',
 'teertha',
 '(',
 '13th',
 'century',
 ')',
 ',',
 'sri',
 'jaya',
 'teertha',
 '(',
 '13th',
 'century',
 ')',
 'srivadiraja',
 'teertha',
 '(',
 '16th',
 'century',
 ')',
 ',',
 'sri',
 'raghavendra',
 'teertha',
 '(',
 '17th',
 'century',
 ')',
 'and',
 'others.the',
 'gita',
 'consists',
 'of',
 '18',
 'chapters',
 'with',
 'a',
 'total',
 'of',
 '7011',
 'verses',
 'insanskrit',
 '.',
 'the',
 'gita',
 'is',
 'part',
 'of',
 'the',
 'great',
 'hindu',
 'epic',
 'the',
 'mahabharata',
 'andappears',
 'as',
 'chapters',
 '25',
 'to',
 '42',
 ',',
 'in',
 'the',
 'book',
 'of',
 'bheeshma',
 'in',
 'themahabharata',
 '.',
 'most',
 'of',
 'the',
 'verses',
 'appear',
 'in',
 'the',
 'anushtap',
 'meter',
 ',',
 'whereeach',
 'verse',
 'has',
 'a',
 'total',
 'of',
 '32',
 'letters',
 'with',
 '8',
 'words',
 'in',
 'each',
 'of',
 'the',
 'fourquadrants',
 '.',
 'some',
 'verses',
 'in',
 'the',
 '15th',
 'chapter',
 'appear',
 'in',
 'trishtup',
 'meter',
 'with',
 '44words',
 '.',
 'as',
 'per',
 'sri',
 'raghavendra',
 'teertha',
 '[',
 'gv',
 ']',
 ',',
 'the',
 '18',
 'chapters',
 'can',
 'bebroadly',
 'classified',
 'into',
 '3',
 'sections',
 'with',
 '6',
 'chapters',
 'in',
 'each',
 'section',
 '.',
 'the',
 'firstsection',
 'with',
 'chapters',
 '1-6',
 '(',
 '280',
 'verses',
 ')',
 'broadly',
 'outlines',
 'how',
 'one',
 'can',
 'obtaindivine',
 ',',
 'spiritual',
 'knowledge',
 ...]

In [33]:
vocab = {'<unk>':0}
Counter(tokens).keys()

dict_keys(['over', 'centuries', ',', 'the', 'bhagavad', 'gita', 'has', 'been', 'considered', 'animportant', 'spiritual', 'guidebook', 'and', 'influenced', 'many', 'thought', 'leaders', 'inhuman', 'history', '.', 'is', 'a', 'conversational', 'poem', 'part', 'of', 'greatindian', 'epic', 'mahabharata', 'which', 'story', 'about', 'families', 'twobrothers', 'who', 'inherit', 'kingdom', 'from', 'their', 'father', 'these', 'cousins', 'are', 'knownas', '‘', 'pandavas', '’', 'kauravas', 'kaurava', 'brothers', '100', 'innumber', '5.', 'not', 'wanting', 'to', 'share', 'thekingdom', 'with', 'invite', 'them', 'game', 'dice', 'they', 'usedubious', 'means', 'defeat', 'annex', 'afterwinning', 'wager', 'as', 'per', 'rules', 'completetheir', 'stay', 'outside', 'come', 'back', 'ask', 'for', 'fair', 'ofthe', 'so', 'that', 'can', 'rule', 'dignity', 'refuse', 'tohonor', 'agreement', 'even', 'deny', 'settlement', '5', 'villagesso', 'live', 'in', 'peace', 'budge', 'aninch', 'have', 'no', 'choice', 'but', 'declare', 'war', 'on', 'get', 'backtheir', 'during', 'this', 'period', 'lord', 'hasincarnated', 'krishna', 'offers', 'between', 'his', 'army', 'andhimself', 'he', 'makes', 'it', 'clear', 'himself', 'would', 'be', 'participatingin', 'choose', 'befighting', 'happy', 'just', 'side.krishna', 'takes', 'role', 'charioteer', 'arjuna', 's', 'chariot', '(', 'thethird', 'brother', 'among', 'five', ')', '.before', 'starts', 'two', 'armies', 'assemble', 'battlefield', 'facing', 'each', 'other', 'at', 'point', 'requests', 'place', 'hischariot', 'middle', 'full', 'view', 'warring', 'forces.since', 'sees', 'uncles', 'grandfathers', 'great', 'nephews', 'friends', 'classmates', 'etc', 'bothsides', 'overcome', 'emotion', 'grief', 'prospect', 'bloodshedamong', 'family', 'sake', 'declares', 'hisintention', 'renounce', 'let', 'keep', 'thus', 'abdicating', 'responsibility', 'prince', 'warrior', 'stage', 'thatkrishna', 'teaches', 'him', 'structured', 'series', 'questionsfrom', 'answers', 'extols', 'virtue', 'ofperforming', 'one', 'duties', 'regardless', 'outcome', 'avoidingprescribed', 'may', 'difficult', 'unpleasant', 'startsto', 'talk', 'virtues', 'doing', 'work', 'case', 'arjunaneeding', 'fight', 'rightful', 'asks', 'questions', 'thebigger', 'issues', 'life', 'individual', 'souls', 'almighty', 'universe', 'thecircle', 'etc.', 'provides', 'unambiguous', 'answers.he', 'finally', 'convinces', 'fears', 'were', 'unfounded', 'heshould', 'free', 'provide', 'andcompassionate', 'administration', 'citizens.at', 'first', 'battleground', 'hardly', 'someone', 'bepreaching', 'philosophy', 'however', 'we', 'lifeare', 'choices', 'make', 'especially', 'challenging', 'times', 'isinteresting', 'note', 'sanskrit', 'verses', 'lend', 'themselves', 'multiplemeanings', 'interpretation', 'iscompared', 'human', 'body', 'mind', 'battle', 'thepandavas', 'compared', 'constant', 'strife', 'goodand', 'evil', 'thoughts', 'encounter', 'daily', 'indeed', 'teaching', 'forall', 'us', 'acting', 'an', 'example', 'crossroads', 'desperately', 'looking', 'guidance', 'support.the', 'most', 'widely', 'read', 'commented', 'uponspiritual', 'works', 'there', 'several', 'excellent', 'books', 'invarious', 'languages', 'given', 'original', 'thescholarly', 'commentaries', 'or', 'indian', 'languageswhich', 'closer', 'comprehend', 'onewould', 'need', 'some', 'training', 'studies', 'themliberally', 'use', 'words', 'albeit', 'transliterated', 'english', 'was', 'felt', 'thatthere', 'present', 'key', 'concepts', 'plain', 'foreveryday', 'folk', 'minimizing', 'observationsled', 'development', 'manuscript', 'while', 'learned', 'written', 'overthe', 'author', 'greatly', 'by', 'authoritativecommentary', 'lucid', 'explanations', 'srimadhwacharya', '12th', 'century', 'ascetic', 'propounded', 'ofdualistic', 'theism', 'concept', 'difference', 'andindividual', 'all', 'places', 'sri', 'madhwacharya', 'commentaryhas', 'further', 'elaborated', 'summarized', 'later', 'day', 'savants', 'such', 'assri', 'padmanabha', 'teertha', '13th', 'jaya', 'srivadiraja', '16th', 'raghavendra', '17th', 'others.the', 'consists', '18', 'chapters', 'total', '7011', 'insanskrit', 'hindu', 'andappears', '25', '42', 'book', 'bheeshma', 'themahabharata', 'appear', 'anushtap', 'meter', 'whereeach', 'verse', '32', 'letters', '8', 'fourquadrants', '15th', 'chapter', 'trishtup', '44words', '[', 'gv', ']', 'bebroadly', 'classified', 'into', '3', 'sections', '6', 'section', 'firstsection', '1-6', '280', 'broadly', 'outlines', 'how', 'obtaindivine', 'knowledge', 'jnana', 'upaya', 'second', 'chapters7-12', '209', 'focuses', 'devotion', 'divine', 'vijnana', 'leads', 'liberation', 'third', 'consisting', 'ofchapters', '13-18', '212', 'elaborates', 'twosections', 'also', 'believed', 'conveys', 'least', '10', 'differentmeanings', 'consistent', 'another', 'illustration', 'ofmultiple', 'meanings', 'will', '2.', 'said', 'thatthe', 'major', 'interpretations', '–', 'historical', 'psychological', 'numbers', 'numerology', 'play', 'incredibly', 'significant', 'inindian', 'theology', 'fact', 'study', 'termed', 'sankhya', 'yoga', 'meaning', 'arithmetic', 'world', 'around', 'based', 'onnumbers', 'constantly', 'measuring', 'managing', 'quantifying', 'ouractivities', 'aid', 'wake', 'up', 'certain', 'time', 'wework/study', 'hours', 'travel', 'distance', 'consumesome', 'amount', 'food', 'transact', 'currency', 'performactivities', 'month', 'certainyear', 'calculations', 'positionand', 'movement', 'celestial', 'objects', 'sun', 'moon', 'stars'])

In [34]:
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)
vocab

{'<unk>': 0,
 'over': 1,
 'centuries': 2,
 ',': 3,
 'the': 4,
 'bhagavad': 5,
 'gita': 6,
 'has': 7,
 'been': 8,
 'considered': 9,
 'animportant': 10,
 'spiritual': 11,
 'guidebook': 12,
 'and': 13,
 'influenced': 14,
 'many': 15,
 'thought': 16,
 'leaders': 17,
 'inhuman': 18,
 'history': 19,
 '.': 20,
 'is': 21,
 'a': 22,
 'conversational': 23,
 'poem': 24,
 'part': 25,
 'of': 26,
 'greatindian': 27,
 'epic': 28,
 'mahabharata': 29,
 'which': 30,
 'story': 31,
 'about': 32,
 'families': 33,
 'twobrothers': 34,
 'who': 35,
 'inherit': 36,
 'kingdom': 37,
 'from': 38,
 'their': 39,
 'father': 40,
 'these': 41,
 'cousins': 42,
 'are': 43,
 'knownas': 44,
 '‘': 45,
 'pandavas': 46,
 '’': 47,
 'kauravas': 48,
 'kaurava': 49,
 'brothers': 50,
 '100': 51,
 'innumber': 52,
 '5.': 53,
 'not': 54,
 'wanting': 55,
 'to': 56,
 'share': 57,
 'thekingdom': 58,
 'with': 59,
 'invite': 60,
 'them': 61,
 'game': 62,
 'dice': 63,
 'they': 64,
 'usedubious': 65,
 'means': 66,
 'defeat': 67,
 'annex': 68,
 'afterwinning': 69,
 'wager': 70,
 'as': 71,
 'per': 72,
 'rules': 73,
 'completetheir': 74,
 'stay': 75,
 'outside': 76,
 'come': 77,
 'back': 78,
 'ask': 79,
 'for': 80,
 'fair': 81,
 'ofthe': 82,
 'so': 83,
 'that': 84,
 'can': 85,
 'rule': 86,
 'dignity': 87,
 'refuse': 88,
 'tohonor': 89,
 'agreement': 90,
 'even': 91,
 'deny': 92,
 'settlement': 93,
 '5': 94,
 'villagesso': 95,
 'live': 96,
 'in': 97,
 'peace': 98,
 'budge': 99,
 'aninch': 100,
 'have': 101,
 'no': 102,
 'choice': 103,
 'but': 104,
 'declare': 105,
 'war': 106,
 'on': 107,
 'get': 108,
 'backtheir': 109,
 'during': 110,
 'this': 111,
 'period': 112,
 'lord': 113,
 'hasincarnated': 114,
 'krishna': 115,
 'offers': 116,
 'between': 117,
 'his': 118,
 'army': 119,
 'andhimself': 120,
 'he': 121,
 'makes': 122,
 'it': 123,
 'clear': 124,
 'himself': 125,
 'would': 126,
 'be': 127,
 'participatingin': 128,
 'choose': 129,
 'befighting': 130,
 'happy': 131,
 'just': 132,
 'side.krishna': 133,
 'takes': 134,
 'role': 135,
 'charioteer': 136,
 'arjuna': 137,
 's': 138,
 'chariot': 139,
 '(': 140,
 'thethird': 141,
 'brother': 142,
 'among': 143,
 'five': 144,
 ')': 145,
 '.before': 146,
 'starts': 147,
 'two': 148,
 'armies': 149,
 'assemble': 150,
 'battlefield': 151,
 'facing': 152,
 'each': 153,
 'other': 154,
 'at': 155,
 'point': 156,
 'requests': 157,
 'place': 158,
 'hischariot': 159,
 'middle': 160,
 'full': 161,
 'view': 162,
 'warring': 163,
 'forces.since': 164,
 'sees': 165,
 'uncles': 166,
 'grandfathers': 167,
 'great': 168,
 'nephews': 169,
 'friends': 170,
 'classmates': 171,
 'etc': 172,
 'bothsides': 173,
 'overcome': 174,
 'emotion': 175,
 'grief': 176,
 'prospect': 177,
 'bloodshedamong': 178,
 'family': 179,
 'sake': 180,
 'declares': 181,
 'hisintention': 182,
 'renounce': 183,
 'let': 184,
 'keep': 185,
 'thus': 186,
 'abdicating': 187,
 'responsibility': 188,
 'prince': 189,
 'warrior': 190,
 'stage': 191,
 'thatkrishna': 192,
 'teaches': 193,
 'him': 194,
 'structured': 195,
 'series': 196,
 'questionsfrom': 197,
 'answers': 198,
 'extols': 199,
 'virtue': 200,
 'ofperforming': 201,
 'one': 202,
 'duties': 203,
 'regardless': 204,
 'outcome': 205,
 'avoidingprescribed': 206,
 'may': 207,
 'difficult': 208,
 'unpleasant': 209,
 'startsto': 210,
 'talk': 211,
 'virtues': 212,
 'doing': 213,
 'work': 214,
 'case': 215,
 'arjunaneeding': 216,
 'fight': 217,
 'rightful': 218,
 'asks': 219,
 'questions': 220,
 'thebigger': 221,
 'issues': 222,
 'life': 223,
 'individual': 224,
 'souls': 225,
 'almighty': 226,
 'universe': 227,
 'thecircle': 228,
 'etc.': 229,
 'provides': 230,
 'unambiguous': 231,
 'answers.he': 232,
 'finally': 233,
 'convinces': 234,
 'fears': 235,
 'were': 236,
 'unfounded': 237,
 'heshould': 238,
 'free': 239,
 'provide': 240,
 'andcompassionate': 241,
 'administration': 242,
 'citizens.at': 243,
 'first': 244,
 'battleground': 245,
 'hardly': 246,
 'someone': 247,
 'bepreaching': 248,
 'philosophy': 249,
 'however': 250,
 'we': 251,
 'lifeare': 252,
 'choices': 253,
 'make': 254,
 'especially': 255,
 'challenging': 256,
 'times': 257,
 'isinteresting': 258,
 'note': 259,
 'sanskrit': 260,
 'verses': 261,
 'lend': 262,
 'themselves': 263,
 'multiplemeanings': 264,
 'interpretation': 265,
 'iscompared': 266,
 'human': 267,
 'body': 268,
 'mind': 269,
 'battle': 270,
 'thepandavas': 271,
 'compared': 272,
 'constant': 273,
 'strife': 274,
 'goodand': 275,
 'evil': 276,
 'thoughts': 277,
 'encounter': 278,
 'daily': 279,
 'indeed': 280,
 'teaching': 281,
 'forall': 282,
 'us': 283,
 'acting': 284,
 'an': 285,
 'example': 286,
 'crossroads': 287,
 'desperately': 288,
 'looking': 289,
 'guidance': 290,
 'support.the': 291,
 'most': 292,
 'widely': 293,
 'read': 294,
 'commented': 295,
 'uponspiritual': 296,
 'works': 297,
 'there': 298,
 'several': 299,
 'excellent': 300,
 'books': 301,
 'invarious': 302,
 'languages': 303,
 'given': 304,
 'original': 305,
 'thescholarly': 306,
 'commentaries': 307,
 'or': 308,
 'indian': 309,
 'languageswhich': 310,
 'closer': 311,
 'comprehend': 312,
 'onewould': 313,
 'need': 314,
 'some': 315,
 'training': 316,
 'studies': 317,
 'themliberally': 318,
 'use': 319,
 'words': 320,
 'albeit': 321,
 'transliterated': 322,
 'english': 323,
 'was': 324,
 'felt': 325,
 'thatthere': 326,
 'present': 327,
 'key': 328,
 'concepts': 329,
 'plain': 330,
 'foreveryday': 331,
 'folk': 332,
 'minimizing': 333,
 'observationsled': 334,
 'development': 335,
 'manuscript': 336,
 'while': 337,
 'learned': 338,
 'written': 339,
 'overthe': 340,
 'author': 341,
 'greatly': 342,
 'by': 343,
 'authoritativecommentary': 344,
 'lucid': 345,
 'explanations': 346,
 'srimadhwacharya': 347,
 '12th': 348,
 'century': 349,
 'ascetic': 350,
 'propounded': 351,
 'ofdualistic': 352,
 'theism': 353,
 'concept': 354,
 'difference': 355,
 'andindividual': 356,
 'all': 357,
 'places': 358,
 'sri': 359,
 'madhwacharya': 360,
 'commentaryhas': 361,
 'further': 362,
 'elaborated': 363,
 'summarized': 364,
 'later': 365,
 'day': 366,
 'savants': 367,
 'such': 368,
 'assri': 369,
 'padmanabha': 370,
 'teertha': 371,
 '13th': 372,
 'jaya': 373,
 'srivadiraja': 374,
 '16th': 375,
 'raghavendra': 376,
 '17th': 377,
 'others.the': 378,
 'consists': 379,
 '18': 380,
 'chapters': 381,
 'total': 382,
 '7011': 383,
 'insanskrit': 384,
 'hindu': 385,
 'andappears': 386,
 '25': 387,
 '42': 388,
 'book': 389,
 'bheeshma': 390,
 'themahabharata': 391,
 'appear': 392,
 'anushtap': 393,
 'meter': 394,
 'whereeach': 395,
 'verse': 396,
 '32': 397,
 'letters': 398,
 '8': 399,
 'fourquadrants': 400,
 '15th': 401,
 'chapter': 402,
 'trishtup': 403,
 '44words': 404,
 '[': 405,
 'gv': 406,
 ']': 407,
 'bebroadly': 408,
 'classified': 409,
 'into': 410,
 '3': 411,
 'sections': 412,
 '6': 413,
 'section': 414,
 'firstsection': 415,
 '1-6': 416,
 '280': 417,
 'broadly': 418,
 'outlines': 419,
 'how': 420,
 'obtaindivine': 421,
 'knowledge': 422,
 'jnana': 423,
 'upaya': 424,
 'second': 425,
 'chapters7-12': 426,
 '209': 427,
 'focuses': 428,
 'devotion': 429,
 'divine': 430,
 'vijnana': 431,
 'leads': 432,
 'liberation': 433,
 'third': 434,
 'consisting': 435,
 'ofchapters': 436,
 '13-18': 437,
 '212': 438,
 'elaborates': 439,
 'twosections': 440,
 'also': 441,
 'believed': 442,
 'conveys': 443,
 'least': 444,
 '10': 445,
 'differentmeanings': 446,
 'consistent': 447,
 'another': 448,
 'illustration': 449,
 'ofmultiple': 450,
 'meanings': 451,
 'will': 452,
 '2.': 453,
 'said': 454,
 'thatthe': 455,
 'major': 456,
 'interpretations': 457,
 '–': 458,
 'historical': 459,
 'psychological': 460,
 'numbers': 461,
 'numerology': 462,
 'play': 463,
 'incredibly': 464,
 'significant': 465,
 'inindian': 466,
 'theology': 467,
 'fact': 468,
 'study': 469,
 'termed': 470,
 'sankhya': 471,
 'yoga': 472,
 'meaning': 473,
 'arithmetic': 474,
 'world': 475,
 'around': 476,
 'based': 477,
 'onnumbers': 478,
 'constantly': 479,
 'measuring': 480,
 'managing': 481,
 'quantifying': 482,
 'ouractivities': 483,
 'aid': 484,
 'wake': 485,
 'up': 486,
 'certain': 487,
 'time': 488,
 'wework/study': 489,
 'hours': 490,
 'travel': 491,
 'distance': 492,
 'consumesome': 493,
 'amount': 494,
 'food': 495,
 'transact': 496,
 'currency': 497,
 'performactivities': 498,
 'month': 499,
 'certainyear': 500,
 'calculations': 501,
 'positionand': 502,
 'movement': 503,
 'celestial': 504,
 'objects': 505,
 'sun': 506,
 'moon': 507,
 'stars': 508}

In [35]:
len(vocab)

509

In [36]:
input_sentences = document.split("\n")

In [37]:
def text_to_indices(sentence, vocab):
  indexed_text = []
  for token in sentence:
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<unk>'])
  return indexed_text

In [38]:
input_sentences

['',
 'Over centuries, the Bhagavad Gita has been considered animportant spiritual guidebook and has influenced many thought leaders inhuman history. The Gita is a conversational poem and is part of the greatIndian epic the Mahabharata, which is a story about the families of twobrothers who inherit a kingdom from their father. These cousins are knownas the ‘Pandavas’ and the ‘Kauravas’. The Kaurava brothers are 100 innumber and the Pandavas are 5. The Kauravas, not wanting to share thekingdom with their cousins, invite them to a game of dice. They usedubious means to defeat the Pandavas and annex their kingdom afterwinning the wager. As per the rules of the wager, the Pandavas completetheir stay outside the kingdom and come back to ask for their fair share ofthe kingdom so that they can rule with dignity. The Kauravas refuse tohonor the agreement and even deny the Pandavas a settlement of 5 villagesso that they can live in peace. As the Kauravas refuse to budge even aninch, the Pandavas have no choice but to declare war on them to get backtheir share of the kingdom. During this period, The Lord who hasincarnated as Krishna offers the cousins a choice between His army andHimself. But He makes it clear that He Himself would not be participatingin the war. The Kauravas choose His army as Krishna would not befighting, and the Pandavas are happy to just have Krishna on their side.Krishna takes on the role of charioteer to Arjuna’s chariot (Arjuna is thethird brother among the five Pandavas).Before the war starts, the two armies assemble on the battlefield,facing each other. At this point, Arjuna requests Krishna to place hischariot in the middle so that he can get a full view of the warring forces.Since this is a war between cousins, Arjuna sees his cousins, uncles,grandfathers, great grandfathers, nephews, friends, classmates etc. on bothsides. He is overcome with emotion and grief at the prospect of bloodshedamong his family and friends for the sake of a kingdom. He declares hisintention to renounce the war and let the Kauravas keep the kingdom, thus abdicating his responsibility as a prince and a warrior. It is at this stage thatKrishna teaches him the Gita which is structured as a series of questionsfrom Arjuna and answers from Krishna. Krishna extols the virtue ofperforming one’s duties regardless of the outcome, and not avoidingprescribed duties which may be difficult and unpleasant. As Krishna startsto talk to Arjuna on the virtues of doing one’s work (in this case Arjunaneeding to fight a rightful war), Arjuna asks a series of questions on thebigger issues of life, individual souls, the Lord Almighty, the universe, thecircle of life etc., for which Krishna provides clear, unambiguous answers.He finally convinces Arjuna that his fears were unfounded and that heshould fight to free the Kingdom from the Kauravas and provide a just andcompassionate administration to his citizens.At first a battleground is hardly the place for someone to bepreaching philosophy. However, many of the questions that we have in lifeare about the choices we have to make, especially in challenging times. It isinteresting to note that Sanskrit verses lend themselves to multiplemeanings and in one interpretation, the battleground in the Gita iscompared to the human body (and mind), and the battle between thePandavas and the Kauravas is compared to the constant strife between goodand evil thoughts that we encounter daily. The Gita is indeed a teaching forall of us, with Arjuna acting as an example of an individual at crossroads,desperately looking for guidance and support.The Gita is one of the most widely read and commented uponspiritual works in human history. There are several excellent books on it invarious languages. Given that the original work is in Sanskrit, most of thescholarly commentaries have been in Sanskrit or other Indian languageswhich are closer to Sanskrit. To read and comprehend many of them, onewould need some training in Indian spiritual studies, as many of themliberally use Sanskrit words albeit transliterated in English. It was felt thatthere is a need to present the key concepts of The Gita in plain English foreveryday folk, minimizing the use of Sanskrit words. These observationsled to the development of this manuscript. While there are many learned commentaries on the Gita written overthe centuries, this author has been greatly influenced by the authoritativecommentary and lucid explanations of difficult concepts by SriMadhwacharya, the 12th century ascetic who propounded the philosophy ofdualistic theism (concept of difference between the almighty Lord andindividual souls at all times and places). Sri Madhwacharya’s commentaryhas been further elaborated and summarized by later day savants such asSri Padmanabha Teertha (13th Century), Sri Jaya Teertha (13th Century) SriVadiraja Teertha (16th Century), Sri Raghavendra Teertha (17th century)and others.The Gita consists of 18 chapters with a total of 7011 verses inSanskrit. The Gita is part of the great Hindu epic The Mahabharata andappears as Chapters 25 to 42, in the Book of Bheeshma in theMahabharata. Most of the verses appear in the anushtap meter, whereeach verse has a total of 32 letters with 8 words in each of the fourquadrants. Some verses in the 15th chapter appear in trishtup meter with 44words. As per Sri Raghavendra Teertha [GV], the 18 chapters can bebroadly classified into 3 sections with 6 chapters in each section. The firstsection with chapters 1-6 (280 verses) broadly outlines how one can obtaindivine, spiritual knowledge (jnana upaya), the second section with chapters7-12 (209 verses) focuses on devotion and divine, spiritual knowledge(vijnana) that leads one to liberation, and the third section consisting ofchapters 13-18 (212 verses) elaborates on the concepts in the first twosections. It is also believed that the Gita conveys at least 10 differentmeanings, all of which are consistent with one another. An illustration ofmultiple meanings in the Gita will appear in Chapter 2. It is also said thatthe Gita has 3 major interpretations – historical, psychological, and spiritual. Numbers and numerology play an incredibly significant role inIndian theology. In fact, the study of knowledge is termed ‘Sankhya Yoga’,with Sankhya meaning ‘arithmetic’. The world around us is based onnumbers. We are constantly measuring, managing, quantifying all ouractivities with the aid of numbers. We wake up at a certain time, wework/study for certain hours, we travel a certain distance, we consumesome amount of food, we transact with certain currency, we performactivities at a certain time, on a certain day, in a certain month, in a certainyear etc. And all these numbers and calculations are based on the positionand movement of celestial objects such as the Sun, Moon, stars etc.']

In [39]:
input_numerical_sentences = []
for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))

In [40]:
input_numerical_sentences

[[],
 [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  7,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  4,
  6,
  21,
  22,
  23,
  24,
  13,
  21,
  25,
  26,
  4,
  27,
  28,
  4,
  29,
  3,
  30,
  21,
  22,
  31,
  32,
  4,
  33,
  26,
  34,
  35,
  36,
  22,
  37,
  38,
  39,
  40,
  20,
  41,
  42,
  43,
  44,
  4,
  45,
  46,
  47,
  13,
  4,
  45,
  48,
  47,
  20,
  4,
  49,
  50,
  43,
  51,
  52,
  13,
  4,
  46,
  43,
  53,
  4,
  48,
  3,
  54,
  55,
  56,
  57,
  58,
  59,
  39,
  42,
  3,
  60,
  61,
  56,
  22,
  62,
  26,
  63,
  20,
  64,
  65,
  66,
  56,
  67,
  4,
  46,
  13,
  68,
  39,
  37,
  69,
  4,
  70,
  20,
  71,
  72,
  4,
  73,
  26,
  4,
  70,
  3,
  4,
  46,
  74,
  75,
  76,
  4,
  37,
  13,
  77,
  78,
  56,
  79,
  80,
  39,
  81,
  57,
  82,
  37,
  83,
  84,
  64,
  85,
  86,
  59,
  87,
  20,
  4,
  48,
  88,
  89,
  4,
  90,
  13,
  91,
  92,
  4,
  46,
  22,
  93,
  26,
  94,
  95,
  84,
  64,
  85,
  96,
  97,
  98,
  20,
  71,
  4,
  48,
  88,
  56,
  99,
  91,
  100,
  3,
  4,
  46,
  101,
  102,
  103,
  104,
  56,
  105,
  106,
  107,
  61,
  56,
  108,
  109,
  57,
  26,
  4,
  37,
  20,
  110,
  111,
  112,
  3,
  4,
  113,
  35,
  114,
  71,
  115,
  116,
  4,
  42,
  22,
  103,
  117,
  118,
  119,
  120,
  20,
  104,
  121,
  122,
  123,
  124,
  84,
  121,
  125,
  126,
  54,
  127,
  128,
  4,
  106,
  20,
  4,
  48,
  129,
  118,
  119,
  71,
  115,
  126,
  54,
  130,
  3,
  13,
  4,
  46,
  43,
  131,
  56,
  132,
  101,
  115,
  107,
  39,
  133,
  134,
  107,
  4,
  135,
  26,
  136,
  56,
  137,
  47,
  138,
  139,
  140,
  137,
  21,
  141,
  142,
  143,
  4,
  144,
  46,
  145,
  146,
  4,
  106,
  147,
  3,
  4,
  148,
  149,
  150,
  107,
  4,
  151,
  3,
  152,
  153,
  154,
  20,
  155,
  111,
  156,
  3,
  137,
  157,
  115,
  56,
  158,
  159,
  97,
  4,
  160,
  83,
  84,
  121,
  85,
  108,
  22,
  161,
  162,
  26,
  4,
  163,
  164,
  111,
  21,
  22,
  106,
  117,
  42,
  3,
  137,
  165,
  118,
  42,
  3,
  166,
  3,
  167,
  3,
  168,
  167,
  3,
  169,
  3,
  170,
  3,
  171,
  172,
  20,
  107,
  173,
  20,
  121,
  21,
  174,
  59,
  175,
  13,
  176,
  155,
  4,
  177,
  26,
  178,
  118,
  179,
  13,
  170,
  80,
  4,
  180,
  26,
  22,
  37,
  20,
  121,
  181,
  182,
  56,
  183,
  4,
  106,
  13,
  184,
  4,
  48,
  185,
  4,
  37,
  3,
  186,
  187,
  118,
  188,
  71,
  22,
  189,
  13,
  22,
  190,
  20,
  123,
  21,
  155,
  111,
  191,
  192,
  193,
  194,
  4,
  6,
  30,
  21,
  195,
  71,
  22,
  196,
  26,
  197,
  137,
  13,
  198,
  38,
  115,
  20,
  115,
  199,
  4,
  200,
  201,
  202,
  47,
  138,
  203,
  204,
  26,
  4,
  205,
  3,
  13,
  54,
  206,
  203,
  30,
  207,
  127,
  208,
  13,
  209,
  20,
  71,
  115,
  210,
  211,
  56,
  137,
  107,
  4,
  212,
  26,
  213,
  202,
  47,
  138,
  214,
  140,
  97,
  111,
  215,
  216,
  56,
  217,
  22,
  218,
  106,
  145,
  3,
  137,
  219,
  22,
  196,
  26,
  220,
  107,
  221,
  222,
  26,
  223,
  3,
  224,
  225,
  3,
  4,
  113,
  226,
  3,
  4,
  227,
  3,
  228,
  26,
  223,
  229,
  3,
  80,
  30,
  115,
  230,
  124,
  3,
  231,
  232,
  233,
  234,
  137,
  84,
  118,
  235,
  236,
  237,
  13,
  84,
  238,
  217,
  56,
  239,
  4,
  37,
  38,
  4,
  48,
  13,
  240,
  22,
  132,
  241,
  242,
  56,
  118,
  243,
  244,
  22,
  245,
  21,
  246,
  4,
  158,
  80,
  247,
  56,
  248,
  249,
  20,
  250,
  3,
  15,
  26,
  4,
  220,
  84,
  251,
  101,
  97,
  252,
  32,
  4,
  253,
  251,
  101,
  56,
  254,
  3,
  255,
  97,
  256,
  257,
  20,
  123,
  258,
  56,
  259,
  84,
  260,
  261,
  262,
  263,
  56,
  264,
  13,
  97,
  202,
  265,
  3,
  4,
  245,
  97,
  4,
  6,
  266,
  56,
  4,
  267,
  268,
  140,
  13,
  269,
  145,
  3,
  13,
  4,
  270,
  117,
  271,
  13,
  4,
  48,
  21,
  272,
  56,
  4,
  273,
  274,
  117,
  275,
  276,
  277,
  84,
  251,
  278,
  279,
  20,
  4,
  6,
  21,
  280,
  22,
  281,
  282,
  26,
  283,
  3,
  59,
  137,
  284,
  71,
  285,
  286,
  26,
  285,
  224,
  155,
  287,
  3,
  288,
  289,
  80,
  290,
  13,
  291,
  6,
  21,
  202,
  26,
  4,
  292,
  293,
  294,
  13,
  295,
  296,
  297,
  97,
  267,
  19,
  20,
  298,
  43,
  299,
  300,
  301,
  107,
  123,
  302,
  303,
  20,
  304,
  84,
  4,
  305,
  214,
  21,
  97,
  260,
  3,
  292,
  26,
  306,
  307,
  101,
  8,
  97,
  260,
  308,
  154,
  309,
  310,
  43,
  311,
  56,
  260,
  20,
  56,
  294,
  13,
  312,
  15,
  26,
  61,
  3,
  313,
  314,
  315,
  316,
  97,
  309,
  11,
  317,
  3,
  71,
  15,
  26,
  318,
  319,
  260,
  320,
  321,
  322,
  97,
  323,
  20,
  123,
  324,
  325,
  326,
  21,
  22,
  314,
  56,
  327,
  4,
  328,
  329,
  26,
  4,
  6,
  97,
  330,
  323,
  331,
  332,
  3,
  333,
  4,
  319,
  26,
  260,
  320,
  20,
  41,
  334,
  56,
  4,
  335,
  26,
  111,
  336,
  20,
  337,
  298,
  43,
  15,
  338,
  307,
  107,
  4,
  6,
  339,
  340,
  2,
  3,
  111,
  341,
  7,
  8,
  342,
  14,
  343,
  4,
  344,
  13,
  345,
  346,
  26,
  208,
  329,
  343,
  347,
  3,
  4,
  348,
  349,
  350,
  35,
  351,
  4,
  249,
  352,
  353,
  140,
  354,
  26,
  355,
  117,
  4,
  226,
  113,
  356,
  225,
  155,
  357,
  257,
  13,
  358,
  145,
  20,
  359,
  360,
  47,
  138,
  361,
  8,
  362,
  363,
  13,
  364,
  343,
  365,
  366,
  367,
  368,
  369,
  370,
  371,
  140,
  372,
  349,
  145,
  3,
  359,
  373,
  371,
  140,
  372,
  349,
  145,
  374,
  371,
  140,
  375,
  349,
  145,
  3,
  359,
  376,
  371,
  140,
  377,
  349,
  145,
  13,
  378,
  6,
  379,
  26,
  380,
  381,
  59,
  22,
  382,
  26,
  383,
  261,
  384,
  20,
  4,
  6,
  21,
  25,
  26,
  4,
  168,
  385,
  28,
  4,
  29,
  386,
  71,
  381,
  387,
  56,
  388,
  3,
  97,
  4,
  389,
  26,
  390,
  97,
  391,
  20,
  292,
  26,
  4,
  261,
  392,
  97,
  4,
  393,
  394,
  3,
  395,
  396,
  7,
  22,
  382,
  26,
  397,
  398,
  59,
  399,
  320,
  97,
  153,
  26,
  4,
  400,
  20,
  315,
  261,
  97,
  4,
  401,
  402,
  392,
  97,
  403,
  394,
  59,
  404,
  20,
  71,
  72,
  359,
  376,
  371,
  405,
  406,
  407,
  3,
  4,
  380,
  381,
  85,
  408,
  409,
  410,
  411,
  412,
  59,
  413,
  381,
  97,
  153,
  414,
  20,
  4,
  415,
  59,
  381,
  416,
  140,
  417,
  261,
  145,
  418,
  419,
  420,
  202,
  85,
  421,
  3,
  11,
  422,
  ...]]

In [41]:
len(input_numerical_sentences)

2

In [42]:
training_sequence = []
for sentence in input_numerical_sentences:
  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [43]:
len(training_sequence)

1236

In [44]:
training_sequence[1]

[1, 2, 3]

In [45]:
len_list = []
for sequence in training_sequence:
  len_list.append(len(sequence))
max(len_list)

1237

In [46]:
padded_training_sequence = []
for sequence in training_sequence:
  padded_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [47]:
len(padded_training_sequence[6])

1237

In [48]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype = torch.long)
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0,   1,  ..., 507,   3, 508],
        [  0,   1,   2,  ...,   3, 508, 172],
        [  1,   2,   3,  ..., 508, 172,  20]])

In [49]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:,-1]

In [50]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0,   1,  ...,   3, 507,   3],
        [  0,   1,   2,  ..., 507,   3, 508],
        [  1,   2,   3,  ...,   3, 508, 172]])

In [51]:
y

tensor([  2,   3,   4,  ..., 508, 172,  20])

In [52]:
class CustomDataset(Dataset):
  def __init__(self, X, y):
    self.X = X
    self.y = y
  def __len__(self):
    return self.X.shape[0]
  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

In [53]:
dataset = CustomDataset(X, y)
dataset[0]

(tensor([0, 0, 0,  ..., 0, 0, 1]), tensor(2))

In [54]:
dataloader = DataLoader(dataset, batch_size = 32, shuffle = True)

In [55]:
for input, output in dataloader:
  print(input, output)

tensor([[  0,   0,   0,  ...,   4, 380, 381],
        [  0,   0,   0,  ..., 343, 347,   3],
        [  0,   0,   0,  ...,  34,  35,  36],
        ...,
        [  0,   0,   0,  ..., 309, 310,  43],
        [  0,   0,   0,  ..., 483,  59,   4],
        [  0,   0,   0,  ..., 381,  97, 153]]) tensor([ 85,   4,  22,  56,  54, 221, 385,  42, 487,   4,  18, 294,   4,  20,
        325,  97, 112, 394,   4, 502,  69, 461,   4,  56, 224,  13, 467, 124,
         13, 311, 484, 414])
tensor([[  0,   0,   0,  ..., 353, 140, 354],
        [  0,   0,   0,  ..., 259,  84, 260],
        [  0,   0,   0,  ...,  45, 474,  47],
        ...,
        [  0,   0,   0,  ...,  13,  84, 238],
        [  0,   0,   0,  ...,  97,  22, 487],
        [  0,   0,   0,  ..., 158, 159,  97]]) tensor([ 26, 261,  20, 164,  97,  20,  31,  53,   3,  20,   3, 225,   6,   4,
         13, 410, 130, 357,  45, 136,  21,   4, 251,   6,   3,  47,  12,  43,
        202, 217, 499,   4])
tensor([[  0,   0,   0,  ..., 223,   3, 224],
        [  0,   0,   0,  ...,   4, 151,   3],
        [  0,   0,   0,  ...,  30,  43, 447],
        ...,
        [  0,   0,   0,  ..., 251, 498, 155],
        [  0,   0,   0,  ..., 186, 187, 118],
        [  0,   0,   0,  ..., 318, 319, 260]]) tensor([225, 152,  59,   4,  88,  13,  26, 195,  36, 137,   4,  26, 243, 379,
         22,   3,  26,  55, 333,  22,   4,  64,  26,  74,   4, 443,  37, 485,
        205,  22, 188, 320])
tensor([[  0,   0,   0,  ..., 127, 208,  13],
        [  0,   0,   0,  ..., 224, 155, 287],
        [  0,   0,   0,  ..., 294,  13, 295],
        ...,
        [  0,   0,   0,  ...,  20,   4,   6],
        [  0,   0,   0,  ...,  15,  26,  61],
        [  0,   0,   0,  ...,   4, 245,  97]]) tensor([209,   3, 296, 145,   3,   4,   4,  13,  38,   4, 338, 115, 403, 256,
         26,  22,   3,   6, 422, 155, 357, 358,  22, 489, 140,   6, 378,  26,
        281,  21,   3,   4])
tensor([[  0,   0,   0,  ...,  59, 487, 497],
        [  0,   0,   0,  ..., 417, 261, 145],
        [  0,   0,   0,  ..., 380, 381,  85],
        ...,
        [  0,   0,   0,  ..., 111, 215, 216],
        [  0,   0,   0,  ...,  71, 115, 210],
        [  0,   0,   0,  ..., 155, 111, 156]]) tensor([  3, 418, 408, 220,  14,   6, 202, 294, 373, 313,  29,  56,  87,  22,
        156, 454,   4, 137,  13, 110,   4,   3, 214,  47, 495, 316, 346, 105,
         21,  56, 211,   3])
tensor([[  0,   0,   0,  ..., 274, 117, 275],
        [  0,   0,   0,  ...,  54, 127, 128],
        [  0,   0,   0,  ..., 297,  97, 267],
        ...,
        [  0,   0,   0,  ...,  56, 183,   4],
        [  0,   0,   0,  ...,   3, 359, 376],
        [  0,   0,   0,  ..., 166,   3, 167]]) tensor([276,   4,  19,  22, 261, 501,   6,  20,   4,  59, 421, 138, 138,   3,
        422,  13, 267, 145, 192, 131, 107,  46, 464,   3,  21,  26, 137, 142,
         54, 106, 371,   3])
tensor([[  0,   0,   0,  ...,  60,  61,  56],
        [  0,   0,   0,  ..., 381,  59,  22],
        [  0,   0,   0,  ..., 391,  20, 292],
        ...,
        [  0,   0,   0,  ..., 480,   3, 481],
        [  0,   0,   0,  ...,  43, 299, 300],
        [  0,   0,   0,  ...,   3, 489,  80]]) tensor([ 22, 382,  26,   3, 111,   4,  20, 426,   4, 349, 111, 329,   3, 407,
        371, 344,  26, 332,  80,   4, 229,  97, 137,  73,  83, 254, 277, 215,
          4,   3, 301, 487])
tensor([[  0,   0,   0,  ..., 341,   7,   8],
        [  0,   0,   0,  ...,  47,  13,   4],
        [  0,   0,   0,  ...,  13,   4,  45],
        ...,
        [  0,   0,   0,  ..., 123,  21, 441],
        [  0,   0,   0,  ..., 104,  56, 105],
        [  0,   0,   0,  ..., 254,   3, 255]]) tensor([342,  45,  48, 381,  59, 406,   4,  20,  41,  13,  46, 282,  13,   3,
         59,  48,  47, 260,  56,  71,  71,  13, 375, 416,  27,   3, 436,   4,
         77, 442, 106,  97])
tensor([[  0,   0,   0,  ...,  22, 487, 488],
        [  0,   0,   0,  ...,   3,  97,  22],
        [  0,   0,   0,  ..., 329, 343, 347],
        ...,
        [  0,   0,   0,  ...,   4,  48, 185],
        [  0,   0,   0,  ..., 490,   3, 251],
        [  0,   0,   0,  ...,  13, 240,  22]]) tensor([  3, 487,   3,  13, 450, 115, 244,  14, 399, 458, 251,  22, 381,  43,
        185,  43, 487, 505,  80,  21,  26,  21, 336,  11,  67, 193,  56, 133,
         26,   4, 491, 132])
tensor([[  0,   0,   0,  ..., 463, 285, 464],
        [  0,   0,   0,  ...,  26, 223,   3],
        [  0,   0,   0,  ..., 284,  71, 285],
        ...,
        [  0,   0,   0,  ...,   4, 226, 113],
        [  0,   0,   0,  ...,  20, 123, 258],
        [  0,   0,   0,  ..., 426, 140, 427]]) tensor([465, 224, 286, 441, 143,  84, 309,   3, 503, 118, 107, 140, 103, 212,
        273, 107, 364,  17, 172,  23, 249,  20,   4, 473, 166, 107, 202, 259,
         83, 356,  56, 261])
tensor([[  0,   0,   0,  ..., 130,   3,  13],
        [  0,   0,   0,  ...,   4, 506,   3],
        [  0,   0,   0,  ...,  26,   4,  27],
        ...,
        [  0,   0,   0,  ...,  26, 422,  21],
        [  0,   0,   0,  ...,  21, 246,   4],
        [  0,   0,   0,  ...,  80,  39,  81]]) tensor([  4, 507,  28,   4, 106, 233, 297,  20, 174, 216, 108, 119,  62, 121,
         41, 208,  59, 285, 247, 315,  21,  97,   4,   4,   6, 349,  26,  71,
         13, 470, 158,  57])
tensor([[  0,   0,   0,  ...,  37,  38,   4],
        [  0,   0,   0,  ...,  13, 501,  43],
        [  0,   0,   0,  ..., 269, 145,   3],
        ...,
        [  0,   0,   0,  ...,  54,  55,  56],
        [  0,   0,   0,  ..., 137,  84, 118],
        [  0,   0,   0,  ...,   6, 452, 392]]) tensor([ 48, 477,  13,  24,  45,  43,  56,   6, 349,  84,   4,   3,  79, 487,
        366,  26, 198,  26, 117,  30,  39, 125,  20,   4,  59,   3, 137, 376,
         90,  57, 235,  97])
tensor([[  0,   0,   0,  ...,   5,   6,   7],
        [  0,   0,   0,  ..., 221, 222,  26],
        [  0,   0,   0,  ..., 267,  19,  20],
        ...,
        [  0,   0,   0,  ...,  47, 138, 361],
        [  0,   0,   0,  ...,   3,  71,  15],
        [  0,   0,   0,  ...,   4, 113,  35]]) tensor([  8, 223, 298,  20, 109,  20, 422,  32, 155,   7, 271,   2, 160,  39,
        199,  13,   3,  84, 118,  13,  71,  22, 107,  26, 117, 447,   4, 255,
         20,   8,  26, 114])
tensor([[  0,   0,   0,  ..., 282,  26, 283],
        [  0,   0,   0,  ...,  16,  17,  18],
        [  0,   0,   0,  ...,  37,  69,   4],
        ...,
        [  0,   0,   0,  ..., 250,   3,  15],
        [  0,   0,   0,  ..., 137, 165, 118],
        [  0,   0,   0,  ...,  53,   4,  48]]) tensor([  3,  19,  70, 140,   3,  42, 430, 369, 129, 487,   3, 103, 289, 181,
         15, 231, 380, 144,  60,  80, 401, 444,  97,   5, 284,  71,  13,  59,
        251,  26,  42,   3])
tensor([[  0,   0,   0,  ...,  26,   4, 220],
        [  0,   0,   0,  ...,   4, 415,  59],
        [  0,   0,   0,  ..., 291,   6,  21],
        ...,
        [  0,   0,   0,  ...,   3, 137, 165],
        [  0,   0,   0,  ..., 121,  21, 174],
        [  0,   0,   0,  ...,  79,  80,  39]]) tensor([ 84, 381, 202, 348,  97, 207, 122,  97, 309, 153, 219, 274, 448, 368,
        162,  42, 371,  95, 283, 305, 345, 145,  97, 377, 261,  22,  80, 237,
        272, 118,  59,  81])
tensor([[  0,   0,   0,  ..., 154, 309, 310],
        [  0,   0,   0,  ..., 263,  56, 264],
        [  0,   0,   0,  ..., 185,   4,  37],
        ...,
        [  0,   0,   0,  ..., 245,  97,   4],
        [  0,   0,   0,  ..., 487, 366,   3],
        [  0,   0,   0,  ..., 307, 101,   8]]) tensor([ 43,  13,   3, 167, 141, 145, 268, 359,  84,  22,   4,   4,   6,  56,
        415,  59,   4, 100, 176, 431,  45,  22, 222, 123,  15, 437, 360, 461,
        335,   6,  97,  97])
tensor([[  0,   0,   0,  ..., 424, 145,   3],
        [  0,   0,   0,  ...,  42,   3, 166],
        [  0,   0,   0,  ..., 214,  21,  97],
        ...,
        [  0,   0,   0,  ...,   7,  22, 382],
        [  0,   0,   0,  ..., 203,  30, 207],
        [  0,   0,   0,  ...,   4, 106,  20]]) tensor([  4,   3, 260, 140, 449, 404,  39, 115, 107,   7, 111, 351,   6,  20,
         30, 172, 275, 111,  22, 153, 304, 482,  20, 461,  92,   4, 155, 478,
        307,  26, 127,   4])
tensor([[  0,   0,   0,  ...,   4,  46,  22],
        [  0,   0,   0,  ...,  86,  59,  87],
        [  0,   0,   0,  ..., 124,   3, 231],
        ...,
        [  0,   0,   0,  ..., 138, 214, 140],
        [  0,   0,   0,  ..., 260,   3, 292],
        [  0,   0,   0,  ...,  26, 178, 118]]) tensor([ 93,  20, 232, 153,   3,   4, 352, 180,  15,  65, 115,   4, 121,  56,
         13, 298, 488,  37,  89, 383,  51,  21,   3, 132,  97, 420,  84,  97,
        173,  97,  26, 179])
tensor([[  0,   0,   0,  ...,  20,  64,  65],
        [  0,   0,   0,  ...,  26,   4, 205],
        [  0,   0,   0,  ..., 155, 287,   3],
        ...,
        [  0,   0,   0,  ...,  20, 123,  21],
        [  0,   0,   0,  ..., 464, 465, 135],
        [  0,   0,   0,  ..., 458, 459,   3]]) tensor([ 66,   3, 288, 138,  34,  97, 424,  26, 262, 388,  29, 228,  22,   3,
         97, 208, 327, 452, 115, 202,  13,  22, 210,  37, 417, 126,  13,   3,
        227, 155, 466, 460])
tensor([[  0,   0,   0,  ..., 248, 249,  20],
        [  0,   0,   0,  ..., 394,   3, 395],
        [  0,   0,   0,  ..., 288, 289,  80],
        ...,
        [  0,   0,   0,  ..., 154,  20, 155],
        [  0,   0,   0,  ..., 202,  56, 433],
        [  0,   0,   0,  ..., 257,  20, 123]]) tensor([250, 396, 290,   3, 493, 349,  26, 190, 137,  21, 106,   7,  97, 326,
        137,  91,  13,   4, 184,  48,  13, 353,  37,  97,   3, 402, 158,   4,
         58, 111,   3, 258])
tensor([[  0,   0,   0,  ..., 107, 123, 302],
        [  0,   0,   0,  ..., 118, 179,  13],
        [  0,   0,   0,  ..., 359, 373, 371],
        ...,
        [  0,   0,   0,  ..., 140, 375, 349],
        [  0,   0,   0,  ...,  20,  41,  42],
        [  0,   0,   0,  ...,  22, 382,  26]]) tensor([303, 170, 140,  20, 251, 319,  20,  20, 197, 306, 113,  97,   3, 395,
        113, 107,   6, 359, 320, 330,  59, 236, 155,  46,   4,   4,  26,  46,
        267, 145,  43, 397])
tensor([[  0,   0,   0,  ..., 251,  43, 479],
        [  0,   0,   0,  ..., 404,  20,  71],
        [  0,   0,   0,  ..., 306, 307, 101],
        ...,
        [  0,   0,   0,  ...,  13, 184,   4],
        [  0,   0,   0,  ...,   4, 148, 149],
        [  0,   0,   0,  ...,   3,   4, 425]]) tensor([480,  72,   8, 317, 123, 194, 203, 101,   7, 107, 204, 434, 115, 217,
        135,   3, 186, 314, 269,  26,   4, 368,  46,  26,   4, 318, 116, 118,
        165,  48, 150, 414])
tensor([[  0,   0,   0,  ...,  26, 383, 261],
        [  0,   0,   0,  ..., 461,  13, 462],
        [  0,   0,   0,  ...,  97,  98,  20],
        ...,
        [  0,   0,   0,  ...,   3,  13,  54],
        [  0,   0,   0,  ...,   6,   7,   8],
        [  0,   0,   0,  ..., 305, 214,  21]]) tensor([384, 463,  71,   4,  37, 117,   2, 163, 371,   3,  42,  71,   4,  56,
         56,  21, 260, 135,  20,  71,   4,  91,  20, 441,  48, 363, 218,  72,
        283, 206,   9,  97])
tensor([[  0,   0,   0,  ...,  13, 209,  20],
        [  0,   0,   0,  ...,  22, 487, 492],
        [  0,   0,   0,  ...,  22, 245,  21],
        ...,
        [  0,   0,   0,  ..., 431, 145,  84],
        [  0,   0,   0,  ...,  20,  41, 334],
        [  0,   0,   0,  ..., 468,   3,   4]]) tensor([ 71,   3, 246,   3,   4, 251, 500, 251,   4,   3,  22, 405, 123, 121,
          4,   4,  48, 292, 196, 475,  84,  20, 472, 307, 361, 359, 101,  13,
        175, 432,  56, 469])
tensor([[  0,   0,   0,  ..., 199,   4, 200],
        [  0,   0,   0,  ..., 126,  54, 130],
        [  0,   0,   0,  ...,  26, 208, 329],
        ...,
        [  0,   0,   0,  ..., 143,   4, 144],
        [  0,   0,   0,  ..., 364, 343, 365],
        [  0,   0,   0,  ..., 101,  56, 254]]) tensor([201,   3, 343, 169, 155, 171, 118,  37, 367,  64, 140,  39, 412,  56,
          4, 423, 157,  47, 265, 488,   3,  71,  11,  20, 445, 183,  80,   4,
        343,  46, 366,   3])
tensor([[  0,   0,   0,  ..., 137, 219,  22],
        [  0,   0,   0,  ...,   3,   4, 348],
        [  0,   0,   0,  ...,  48,  88,  56],
        ...,
        [  0,   0,   0,  ...,  46,  74,  75],
        [  0,   0,   0,  ..., 496,  59, 487],
        [  0,   0,   0,  ..., 314,  56, 327]]) tensor([196, 349,  99, 234,  28,  47, 295, 140,  25, 486,   4,  26,  96,   3,
        260,   4,  52, 263, 126,  46, 145,  35,  78,  37, 462,   3,  13,  20,
        121,  76, 497,   4])
tensor([[  0,   0,   0,  ...,  26, 306, 307],
        [  0,   0,   0,  ...,   3,   4, 113],
        [  0,   0,   0,  ..., 440,  20, 123],
        ...,
        [  0,   0,   0,  ...,  76,   4,  37],
        [  0,   0,   0,  ..., 140, 438, 261],
        [  0,   0,   0,  ...,   4,   6,  21]]) tensor([101, 226,  21,   4, 392, 118, 240,  94,   4,  20, 189,   3, 251, 414,
         20,  56, 376,   4, 299, 357,  13, 479,  30,  54,  13,   4, 324,  22,
        453,  13, 145,  22])
tensor([[  0,   0,   0,  ...,  26,   4,   6],
        [  0,   0,   0,  ...,  80, 247,  56],
        [  0,   0,   0,  ..., 475, 476, 283],
        ...,
        [  0,   0,   0,  ..., 474,  47,  20],
        [  0,   0,   0,  ..., 256, 257,  20],
        [  0,   0,   0,  ...,  26,  94,  95]]) tensor([ 97, 248,  21, 411, 107,   3, 145,  97, 117, 370, 321, 398, 118,  44,
        371,  22,  54,   6,   8,  20,  56,  20, 178,  20,  59, 455, 359,   4,
        104,   4, 123,  84])
tensor([[  0,   0,   0,  ...,  85, 108,  22],
        [  0,   0,   0,  ...,   8,   9,  10],
        [  0,   0,   0,  ...,  73,  26,   4],
        ...,
        [  0,   0,   0,  ...,  59, 137, 284],
        [  0,   0,   0,  ...,  85,  96,  97],
        [  0,   0,   0,  ..., 113, 356, 225]]) tensor([161,  11,  70, 279, 343, 292,   4, 357, 334, 314, 329,  26, 101, 350,
        389,  56,  48,  32, 456,   4,  56,  38,   3,  86, 468, 329,  84, 214,
        291,  71,  98, 155])
tensor([[  0,   0,   0,  ...,  64,  65,  66],
        [  0,   0,   0,  ..., 135,  26, 136],
        [  0,   0,   0,  ..., 262, 263,  56],
        ...,
        [  0,   0,   0,  ...,  28,   4,  29],
        [  0,   0,   0,  ..., 146,   4, 106],
        [  0,   0,   0,  ...,  56, 388,   3]]) tensor([ 56,  56, 264, 504, 140, 149, 139, 319,  20, 124, 392,  22, 365,  97,
        145, 187,  26,   3, 278,   4, 440,  16,   3,   4,  68,  33, 104,  59,
          4, 386, 147,  97])
tensor([[  0,   0,   0,  ..., 251, 101,  97],
        [  0,   0,   0,  ..., 498, 155,  22],
        [  0,   0,   0,  ..., 104, 121, 122],
        ...,
        [  0,   0,   0,  ..., 102, 103, 104],
        [  0,   0,   0,  ...,  21, 470,  45],
        [  0,   0,   0,  ..., 150, 107,   4]]) tensor([252, 487, 123, 241, 226, 200,  30, 390, 121,  59, 119, 387,  84, 145,
        372, 494,   3, 242,  20, 476, 315,  26, 270, 202,  26, 102, 245, 380,
        322,  56, 471, 151])
tensor([[  0,   0,   0,  ..., 173,  20, 121],
        [  0,   0,   0,  ..., 164, 111,  21],
        [  0,   0,   0,  ...,  22, 281, 282],
        ...,
        [  0,   0,   0,  ..., 137, 157, 115],
        [  0,   0,   0,  ..., 368,  71,   4],
        [  0,   0,   0,  ...,  56, 105, 106]]) tensor([ 21,  22,  26,   3,  47,   4,  26,  21, 308,  21, 120,  75,  85,  39,
        134,   4,  20, 203, 249, 285,  22, 154, 402,  13, 128, 391, 381, 140,
          3,  56, 506, 107])
tensor([[  0,   0,   0,  ..., 243, 244,  22],
        [  0,   0,   0,  ..., 145,   3,   4],
        [  0,   0,   0,  ..., 504, 505, 368],
        ...,
        [  0,   0,   0,  ..., 201, 202,  47],
        [  0,   0,   0,  ..., 370, 371, 140],
        [  0,   0,   0,  ..., 491,  22, 487]]) tensor([245, 425,  71,   4,  20, 111,  85, 483,  26,  61, 481,   4,  21,  61,
          3,  38, 393,  22, 339, 341,  30, 266,  11, 300, 170, 293, 496, 230,
        374, 138, 372, 492])
tensor([[  0,   0,   0,  ...,   3, 228,  26],
        [  0,   0,   0,  ..., 155, 444, 445],
        [  0,   0,   0,  ...,  22,  62,  26],
        ...,
        [  0,   0,   0,  ...,  97, 260, 308],
        [  0,   0,   0,  ...,  20, 121, 181],
        [  0,   0,   0,  ..., 321, 322,  97]]) tensor([223, 446,  63, 439, 257,   3, 145,   4,   4,   7,  43, 113, 115,   4,
          4, 244, 168, 411, 140, 471,  13,  26,  61, 381, 261,  15,  47, 328,
        177, 154, 182, 323])
tensor([[  0,   0,   0,  ..., 427, 261, 145],
        [  0,   0,   0,  ...,  59, 399, 320],
        [  0,   0,   0,  ..., 294,  13, 312],
        ...,
        [  0,   0,   0,  ...,  56, 294,  13],
        [  0,   0,   0,  ...,  39,  40,  20],
        [  0,   0,   0,  ..., 285, 224, 155]]) tensor([428,  97,  15, 508,  20,  20,  50,   4, 146, 123, 382,  46, 137, 355,
          4, 127, 239,  22,  26,   4, 172,  13, 238,  88, 117, 292,   3,   3,
        260, 312,  41, 287])
tensor([[  0,   0,   0,  ..., 300, 301, 107],
        [  0,   0,   0,  ...,  26, 318, 319],
        [  0,   0,   0,  ..., 131,  56, 132],
        ...,
        [  0,   0,   0,  ...,  13,  68,  39],
        [  0,   0,   0,  ...,   4, 305, 214],
        [  0,   0,   0,  ..., 497,   3, 251]]) tensor([123, 260, 101,  40,  20, 392, 107,  35,  85, 137, 331,  20,   4,  13,
        145,  10,  80, 394,  43,  82, 140, 191, 148,  13,   4,  47,  56, 167,
         11,  37,  21, 498])
tensor([[  0,   0,   0,  ..., 219,  22, 196],
        [  0,   0,   0,  ..., 419, 420, 202],
        [  0,   0,   0,  ...,   6,  97, 330],
        ...,
        [  0,   0,   0,  ..., 476, 283,  21],
        [  0,   0,   0,  ..., 258,  56, 259],
        [  0,   0,   0,  ..., 261, 145, 418]]) tensor([ 26,  85, 323, 115, 340, 427,  26, 459, 220, 435, 155, 140, 168,  49,
        140,  64,  20,  84,  21, 310,  21, 433,   3, 159,   3, 106, 285, 261,
        413, 477,  84, 419])
tensor([[  0,   0,   0,  ..., 381,  85, 408],
        [  0,   0,   0,  ...,  56, 108, 109],
        [  0,   0,   0,  ...,   6,  21,  25],
        ...,
        [  0,   0,   0,  ...,   4,   6,  21],
        [  0,   0,   0,  ..., 138, 361,   8],
        [  0,   0,   0,  ...,   7, 411, 456]]) tensor([409,  57,  26, 145, 251,  35, 337,  13,  20,  56, 261, 107, 106,  26,
        451, 490,  56, 429,   4, 302,  20, 257,   4, 347, 400, 111,  56,  59,
        202,  25, 362, 457])
tensor([[  0,   0,   0,  ..., 158,  80, 247],
        [  0,   0,   0,  ...,   4,   6,  21],
        [  0,   0,   0,  ...,  26, 461,  20],
        ...,
        [  0,   0,   0,  ..., 319,  26, 260],
        [  0,   0,   0,  ...,   4, 212,  26],
        [  0,   0,   0,  ...,  59,  87,  20]]) tensor([ 56, 280, 251,  26, 354,  43,  20, 474,  43,   3,   4, 285,  13, 107,
        438, 108, 253, 320, 213,   4])

In [56]:
import torch.nn as nn
class LSTMModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    # Fix: Embedding dimension should match LSTM input_size
    self.embedding = nn.Embedding(vocab_size, 100)
    self.lstm = nn.LSTM(100, 64, batch_first=True)
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, x): # Fix: Added x as input argument
    embedded = self.embedding(x) # Fix: Use the passed x instead of global X
    output, (hidden, cell) = self.lstm(embedded)
    # hidden shape: (num_layers * num_directions, batch_size, hidden_size)
    # For a single layer, uni-directional LSTM, it's (1, batch_size, hidden_size)
    output = self.fc(hidden.squeeze(0)) # Squeeze the first dimension
    return output

In [57]:
model = LSTMModel(len(vocab))
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

LSTMModel(
  (embedding): Embedding(509, 100)
  (lstm): LSTM(100, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=509, bias=True)
)

In [58]:
epochs = 50
learning_rate = 0.001 # Reduced learning rate
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [59]:
for epoch in range(epochs):
  total_loss = 0
  for input_data, target_labels in dataloader: # Renamed 'output' to 'target_labels' for clarity
    input_data = input_data.to(device)
    target_labels = target_labels.to(device) # Move target_labels to device
    optimizer.zero_grad()
    model_outputs = model(input_data) # Renamed 'output' to 'model_outputs' for clarity
    loss = criterion(model_outputs, target_labels) # Fix: Use model_outputs and target_labels
    loss.backward()
    optimizer.step()
    total_loss = total_loss + loss.item()
  print(f"Epoch: {epoch + 1}, Loss: {total_loss: .4f}")

Epoch: 1, Loss:  241.4754
Epoch: 2, Loss:  226.2052
Epoch: 3, Loss:  207.6998
Epoch: 4, Loss:  199.7188
Epoch: 5, Loss:  192.7254
Epoch: 6, Loss:  185.9798
Epoch: 7, Loss:  178.7901
Epoch: 8, Loss:  171.4679
Epoch: 9, Loss:  164.6870
Epoch: 10, Loss:  157.6979
Epoch: 11, Loss:  150.7908
Epoch: 12, Loss:  143.9098
Epoch: 13, Loss:  137.5026
Epoch: 14, Loss:  131.0812
Epoch: 15, Loss:  124.5512
Epoch: 16, Loss:  118.3652
Epoch: 17, Loss:  112.3932
Epoch: 18, Loss:  106.4339
Epoch: 19, Loss:  100.9740
Epoch: 20, Loss:  95.6122
Epoch: 21, Loss:  90.3826
Epoch: 22, Loss:  85.5044
Epoch: 23, Loss:  80.4109
Epoch: 24, Loss:  75.9162
Epoch: 25, Loss:  71.4838
Epoch: 26, Loss:  67.0259
Epoch: 27, Loss:  63.0183
Epoch: 28, Loss:  59.2359
Epoch: 29, Loss:  55.4217
Epoch: 30, Loss:  52.0717
Epoch: 31, Loss:  48.8022
Epoch: 32, Loss:  45.7546
Epoch: 33, Loss:  42.7917
Epoch: 34, Loss:  40.0971
Epoch: 35, Loss:  37.7507
Epoch: 36, Loss:  35.4244
Epoch: 37, Loss:  33.1490
Epoch: 38, Loss:  31.2389
Epoch: 39, Loss:  29.4934
Epoch: 40, Loss:  27.5609
Epoch: 41, Loss:  25.9987
Epoch: 42, Loss:  24.4208
Epoch: 43, Loss:  22.9969
Epoch: 44, Loss:  21.6682
Epoch: 45, Loss:  20.4778
Epoch: 46, Loss:  19.3383
Epoch: 47, Loss:  18.3445
Epoch: 48, Loss:  17.2002
Epoch: 49, Loss:  16.3003
Epoch: 50, Loss:  15.4722

In [60]:
model.eval() # Set the model to evaluation mode
total = 0
correct = 0
with torch.no_grad():
  for input_data, target_labels in dataloader:
    input_data = input_data.to(device)
    target_labels = target_labels.to(device)
    model_outputs = model(input_data)
    _, predicted = torch.max(model_outputs, 1)
    total += target_labels.size(0)
    correct += (predicted == target_labels).sum().item()

accuracy = correct / total
print(f"Training Accuracy: {accuracy*100:.2f}%")
model.train() # Set the model back to training mode

Training Accuracy: 99.43%

LSTMModel(
  (embedding): Embedding(509, 100)
  (lstm): LSTM(100, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=509, bias=True)
)

In [61]:
def predict_next_word(model, input_sentence, vocab, max_len):
  model.eval() # Set the model to evaluation mode
  tokens = word_tokenize(input_sentence.lower()) # Tokenize and lowercase
  numerical_input = [vocab.get(token, vocab['<unk>']) for token in tokens]

  # Pad the input sequence
  if len(numerical_input) > max_len - 1: # -1 because the last element is the target
      numerical_input = numerical_input[-(max_len - 1):] # Take the last max_len-1 tokens
  padded_input = [0] * (max_len - 1 - len(numerical_input)) + numerical_input

  input_tensor = torch.tensor(padded_input, dtype=torch.long).unsqueeze(0).to(device)

  with torch.no_grad():
    output = model(input_tensor)
    # Get the predicted word index
    predicted_index = torch.argmax(output, dim=1).item()

  # Invert the vocab dictionary to map indices back to words
  idx_to_word = {idx: word for word, idx in vocab.items()}

  predicted_word = idx_to_word.get(predicted_index, '<unk>')
  return predicted_word

In [63]:
predict_next_word(model, "what is a", vocab, max_len = 40)

'to'

In [64]:
predict_next_word(model, "what is", vocab, max_len = 1)

'termed'

Let's test the prediction function with an example. We will use the `max_len` from our training data preparation.

In [65]:
# We need the max_len calculated during data preparation
max_len = max(len_list) # This variable was generated earlier

# Example usage:
input_text = "what is"
next_word = predict_next_word(model, input_text, vocab, max_len)
print(f"Input: '{input_text}'")
print(f"Predicted next word: '{next_word}'")

input_text = "how to avoid"
next_word = predict_next_word(model, input_text, vocab, max_len)
print(f"Input: '{input_text}'")
print(f"Predicted next word: '{next_word}'")

input_text = "what is training"
next_word = predict_next_word(model, input_text, vocab, max_len)
print(f"Input: '{input_text}'")
print(f"Predicted next word: '{next_word}'")

input_text = "what is a neural"
next_word = predict_next_word(model, input_text, vocab, max_len)
print(f"Input: '{input_text}'")
print(f"Predicted next word: '{next_word}'")

input_text = "what is cross"
next_word = predict_next_word(model, input_text, vocab, max_len)
print(f"Input: '{input_text}'")
print(f"Predicted next word: '{next_word}'")

Input: 'what is'
Predicted next word: 'centuries'
Input: 'how to avoid'
Predicted next word: 'centuries'
Input: 'what is training'
Predicted next word: ','
Input: 'what is a neural'
Predicted next word: 'centuries'
Input: 'what is cross'
Predicted next word: 'centuries'

In [69]:
import time
import builtins # Import the builtins module

num_tokens = 10
input_text = builtins.input("Enter the sentence:") # Use builtins.input
for i in range(num_tokens):
  # Corrected argument order and max_len
  output_text = predict_next_word(model, input_text, vocab, max_len)
  print(output_text)
  # To generate a sequence, we should append the predicted word to the input_text
  # and use that as the input for the next prediction.
  input_text = input_text + " " + output_text
  time.sleep(0.5)

Enter the sentence:what is gita
centuries
,
the
bhagavad
gita
has
been
considered
animportant
spiritual